---
title: "Mexican Report"
author: "Citizenship and Civic Participation"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}}
  - \posttitle{\end{flushleft}}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{array}
  - \usepackage{caption} 
  - \usepackage{booktabs} 
  - \usepackage{longtable}
  - \usepackage{threeparttablex}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(palmerpenguins)
library("kableExtra") 
library(stringr)
library(knitr)
library(palmerpenguins)
options(tinytex.verbose = TRUE)


usa_data <- read.csv("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/final_Mexican_IL_2000_22.csv") %>% 
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) 
# install.packages("knitr")

# 
# <<<<<<< HEAD
# =======
# 
# >>>>>>> 878e3cc8db24aa0ba803dd993abc3403948e3942
```

\renewcommand{\arraystretch}{1.4}
\clearpage

# 6. Citizenship and Civic Participation

## 6.A:Number and percentages of Mexicans by status

```{r}
# Define df at the top
df <- usa_data %>% 
  select(race_ethnicity, citizen, perwt, year) %>%
  mutate(
    citizenship_status = case_when(
      citizen == 0 ~ "Citizen", 
      citizen == 1 ~ "Citizen",
      citizen == 2 ~ "Citizen",
      citizen == 3 ~ "Not a Citizen"
    )
  )


# 2022
  survey_design <- df %>%
    as_survey_design(weights = perwt)
  
  numerator_2022 <- survey_design %>%
    filter(year == 2022 & citizen %in% c(0, 1,2) ) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2022 <- survey_design %>%
     filter(year == 2022)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2022 <- numerator_2022 %>%
    left_join(denominator_2022, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2022)
  
  
# 2012
  
  numerator_2012 <- survey_design %>%
    filter(year == 2012 & citizen %in% c(0, 1,2)) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2012 <- survey_design %>%
     filter(year == 2012)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2012 <- numerator_2012 %>%
    left_join(denominator_2012, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2012)
  
  
  
# 2000
   numerator_2000 <- survey_design %>%
    filter(year == 2000 & citizen %in% c(0, 1,2)) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2000 <- survey_design %>%
     filter(year == 2000)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2000 <- numerator_2000 %>%
    left_join(denominator_2000, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2000)
   
  

# Combine all years
citizenship <- bind_rows(df_rates_2022, df_rates_2012, df_rates_2000)
```



```{r}
 table_6.a1  <- citizenship %>%
  ungroup() %>%
  filter(citizenship_status != "Unknown") %>% 
  select(year, race_ethnicity,  citizenship_status, rate) %>%
  pivot_wider(id_cols = race_ethnicity,   names_from =c(citizenship_status, year) , values_from = rate) %>% 
  mutate(change_non_citizen = round(`Citizen_2022` - `Citizen_2000`, 2)) %>% 
    
    select(race_ethnicity, Citizen_2000 , Citizen_2012,   Citizen_2022 ,change_non_citizen) %>%
  mutate(across(-race_ethnicity, ~ paste0(format(round(., 1), nsmall = 1), "%"))) %>% 
  
  kbl(booktabs = T,
      col.names = c("", "2000", "2008-2012", "2018-2022", "Change from 2000 to 2018-2022"),
      align = c("l",rep("r",4)),
      caption = "U.S. Citizenship for Mexicans and Other Racial/Ethnic Groups in Chicago, 2000 (Decennial Census), 2008-2012, and 2018-2022 (ACS 5-year Estimates)",
      format.args = list(big.mark = ","),
      linesep = "") %>%
 kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:5, width = "6.45em") %>%
  add_header_above(align = c("l", rep("c",1)), c("Race/Ethnicity", "Citizen Rate" = 4), 
                   bold = T, font_size =8) %>%
  row_spec(0, align = "c",
           # background = "#f2f0f7",
           font_size = 8) %>%

   add_footnote(
  c("\\footnotesize{Data Source: IPUMS USA, University of Minnesota, www.ipums.org (2000 Decennial Census, 2008-2012, and 2018-2022 American Community Survey 5-year Estimates). Tabulations by Great Cities Institute.}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)
           

table_6.a1                                                                                                 
```


## 6B: Illinois Voting



```{r}
# Define the data directly
state <- c("New Jersey", "Connecticut", "Arizona", "Virginia", "Texas", 
           "New York", "Pennsylvania", "Washington", "Colorado", 
           "California", "Massachusetts", "New Mexico", "Michigan", 
           "Florida", "North Carolina", "Illinois", "Nevada", "Georgia")

total_citizen_population <- c(996, 347, 1340, 425, 5599, 
                              1608, 497, 485, 618, 8305, 
                              449, 539, 302, 3394, 492, 
                              1016, 515, 403)

# Multiply the Total_Citizen_Population by 1000
total_citizen_population <- total_citizen_population * 1000

percent_registered <- c(82.0, 67.8, 66.8, 63.8, 63.2, 
                        61.6, 61.4, 61.0, 60.5, 60.4, 
                        60.4, 59.9, 58.9, 58.7, 54.3, 
                        52.4, 52.0, 47.6)

percent_voted <- c(72.1, 56.4, 60.8, 51.3, 53.1, 
                   54.9, 54.3, 53.7, 51.1, 54.6, 
                   50.7, 53.8, 54.7, 52.7, 48.8, 
                   46.8, 46.4, 44.2)

rank_percent_registered <- c(1, 2, 3, 4, 5, 
                              6, 7, 8, 9, 10, 
                              10, 12, 13, 14, 15, 
                              16, 17, 18)

rank_percent_voted <- c(1, 3, 2, 12, 10, 
                        4, 7, 9, 13, 6, 
                        14, 8, 5, 11, 15, 
                        16, 17, 18)




# Create the DataFrame
election_df <- data.frame(
  STATE = state,
  Total_Citizen_Population = total_citizen_population,
  Percent_Registered = percent_registered,
  Percent_Voted = percent_voted,
  Rank_Percent_Registered = rank_percent_registered,
  Rank_Percent_Voted = rank_percent_voted
)

colnames(election_df)

# kable

  # using kable
table_6b <- election_df %>%  kbl(, booktabs = T,
      col.names = c("", "Number", "% Registered to Vote" , "% Voted", "Rank for % Registered", "Rank for % Voted"),
      align = c("l", rep("r", 5)),
      caption = "Population, Percent Registered to Vote, and Percent Voted for Hispanics by State for the 2020 Presidential Election",
     format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  row_spec(0, 
           align = "c",
           # background = "#f2f0f7",
           font_size = 8) %>% 
  column_spec(1, width = "10em") %>%
  column_spec(2:6, width_min = "6em") %>%
  add_header_above(align = c("l", rep("c",1)), c("State", "Citizens Aged 18 and Older" = 5), 
                   bold = T, font_size =8) %>%
   row_spec(16, background = "#f2f0f7", bold = T) %>%  # Highlight 16th row in light blue
  add_footnote(
  c("\\footnotesize{Data source: U.S. Census Bureau, 'Voting and Registration in Election of November 2020,' Table 4a 'Voting and Registration By States,' GCI tabulation of states with more than 300,000 Latino citizens over age 18.}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)


table_6b
```



## 6C: Chicago Voting

```{r}
# Define the data
category <- c("Percent vote for Brandon Johnson",
              "Percent registered voter turnout",
              "Percent of population aged 18 and over that voted")

hispanic_latino <- c("45.6%", "20.5%", "11.3%")
black_non_hispanic_latino <- c("88.0%", "29.0%", "24.5%")
white_non_hispanic_latino <- c("34.0%", "61.1%", "52.7%")
total <- c("52.0%", "38.7%", "28.0%")

# Create the DataFrame
voting_df <- data.frame(
  Category = category,
  Hispanic_or_Latino = hispanic_latino,
  Black_non_Hispanic_or_Latino = black_non_hispanic_latino,
  White_non_Hispanic_or_Latino = white_non_hispanic_latino,
  Total = total,
  stringsAsFactors = FALSE  # Avoid converting strings to factors
)


  # using kable
table_6c <- voting_df %>%  
  filter(Category != "Percent vote for Brandon Johnson") %>% 
  kbl(, booktabs = T,
      col.names = c("", "Hispanic or Latino", "Black (non-Hispanic or Latino)" , "White (non-Hispanic or Latino)", "Total"),
      align = c("l", rep("r", 4)),
      caption = "Estimates of Voter Turnout and Percent of Adult Population That Voted in 2023 Chicago Mayoral Race",
     format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  row_spec(0, bold = T, align = "c",
           # background = "#f2f0f7",
           font_size = 7.5, monospace = FALSE, strikeout = FALSE) %>%
  column_spec(1, width = "9em") %>%
  column_spec(2:5, width = "7.75em") %>%
  add_footnote(
  c("\\footnotesize{Data Source: Chicago's 2023 Mayoral Race: A Progressive Victory Amidst Shocking Low Turnout by Black and Latino Voters (Calculations from Chicago Board of Election Commissioners 2023 Municipal Runoff Election Results and 2020 U.S. Census.)}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)


table_6c

```

6D: Mexican and Hispanic/Latino Representation in the Illinois Legislature, 2024

```{r}

illinois_legislature <- data.frame(
  Body = c("Senate", "House"),
  Members = c(59, 118),
  Mexicans = c(4, 8),
  Other_Hispanic_or_Latino = c(2, 4),
  Percent_Hispanic_or_Latino = c("10.2%", "10.2%")
)


table_6D <- illinois_legislature %>%  
  kbl(, booktabs = T,
      col.names = c("Body", "Members", "Mexicans" , "Other Hispanic or Latino", "Percent Hispanic or Latino"),
      align = c("l", rep("r", 4)),
      caption = "Mexican and Hispanic/Latino Representation in the Illinois Legislature, 2024",
     format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  row_spec(0, bold = T, align = "c",
           # background = "#f2f0f7",
           font_size = 7.5, monospace = FALSE, strikeout = FALSE) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2:5, width = "8em") %>%
  add_footnote(
  c("\\footnotesize{Data Source: Illinois Legislative Latino Caucus Foundation. Tabulation by Great Cities Institute}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)

table_6D
```






