---
title: "Mexican Report"
author: "Missing Tables-David"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
header-includes: 
  - \usepackage{caption} 
  - \usepackage{booktabs} 
  - \usepackage{longtable}
  - \usepackage{threeparttablex} 
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
editor_options: 
  chunk_output_type: console
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


\renewcommand{\arraystretch}{1.4}
\clearpage

```{r}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(tinytex)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(tmap)
library("kableExtra") 
library(tmaptools)
library("RColorBrewer") 
# library(OpenStreetMap)
# remotes::install_github('yihui/knitr')
# install.packages("knitr")
# library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("demographic_visual.tex")
options(knitr.kable.NA = '-')
 
##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>% 
  st_transform(crs = 4326)
# mapview(community_shp)


```


\renewcommand{\arraystretch}{1.4}
\clearpage


## 6B: Illinois Voting



```{r}
# Create vectors for each column
state <- c("New Jersey", "Michigan", "Connecticut", "Arizona", "Virginia", 
           "Texas", "New York", "Pennsylvania", "Washington", "Massachusetts", 
           "Colorado", "California", "New Mexico", "Florida", "North Carolina", 
           "Illinois", "Georgia")

citizens <- c(996000, 302000, 347000, 1340000, 425000, 
              5599000, 1608000, 497000, 485000, 449000, 
              618000, 8305000, 539000, 3394000, 492000, 
              1016000, 403000)

percent_registered <- c(82, 74.7, 67.8, 66.8, 63.8, 
                        63.2, 61.6, 61.4, 61, 60.4, 
                        60.5, 60.4, 59.9, 58.7, 54.3, 
                        52.4, 47.6)

percent_voting <- c(72.1, 67.9, 56.4, 60.8, 51.3, 
                    53.1, 54.9, 54.3, 53.7, 50.7, 
                    51.1, 60.8, 45.6, 52.7, 48.8, 
                    46.8, 44.2)

rank_registered <- c(1, 2, 3, 4, 5, 
                     6, 7, 8, 9, 10, 
                     11, 12, 13, 14, 15, 
                     16, 17)

rank_voting <- c(1, 2, 5, 3, 11, 
                 9, 6, 7, 8, 13, 
                 12, 3, 16, 10, 14, 
                 15, 17)

# Create the DataFrame
election_df <- data.frame(State = state,
                           # Convert numeric vectors to appropriate data types
                           Citizens = citizens,
                           Percent_Registered = percent_registered,
                           Percent_Voting = percent_voting,
                           Rank_Registered = rank_registered,
                           Rank_Voting = rank_voting)



# kable

  # using kable
table_6b <- election_df %>%  kbl(, booktabs = T,
      col.names = c("State", "# of Citizens", "% Registered" , "% Voting", "Rank Registered", "Rank Voting"),
      align = c("l", rep("r", 5)),
      caption = "2020 Presidential Election /Latino Registration and Voting By States",
     format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "12.5em") %>%
  column_spec(2:5, width = "8.1em") %>%
   row_spec(16, background = "#f2f0f7") %>%  # Highlight 16th row in light blue
  add_footnote(
  c("\\footnotesize{Data source: U.S. Census Bureau, 'Voting and Registration in Election of November 2020,' Table 4a 'Voting and Registration By States,' GCI tabulation of states with more than 300,000 Latino citizens over age 18}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)


table_6b
```









## 6C: Chicago Voting

```{r}
# Define the data
category <- c("Percent vote for Brandon Johnson", 
              "Percent registered voter turnout", 
              "Percent of population aged 18 and over that voted")

hispanic_latino <- c("45.6%", "20.5%", "11.3%")
black_non_hispanic_latino <- c("88.0%", "29.0%", "24.5%")
white_non_hispanic_latino <- c("34.0%", "61.1%", "52.7%")
total <- c("52.0%", "38.7%", "28.0%")

# Create the DataFrame
voting_df <- data.frame(
  Category = category,
  Hispanic_or_Latino = hispanic_latino,
  Black_non_Hispanic_or_Latino = black_non_hispanic_latino,
  White_non_Hispanic_or_Latino = white_non_hispanic_latino,
  Total = total,
  stringsAsFactors = FALSE  # Avoid converting strings to factors
)


  # using kable
table_6c <- voting_df %>%  kbl(, booktabs = T,
      col.names = c("", "Hispanic \nor Latino", "Black  (non-Hispanic or Latino)" , "White (non-Hispanic or Latino)", "Total"),
      align = c("l", rep("r", 4)),
      caption = "Estimates of percent vote for Brandon Johnson, voter turnout, and percent of adult population that voted",
     format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "12.5em", bold = TRUE) %>%
  column_spec(2:5, width = "8.1em") %>%
  add_footnote(
  c("\\footnotesize{Data Source: Chicago's 2023 Mayoral Race: A Progressive Victory Amidst Shocking Low Turnout by Black and Latino Voters (Calculations from Chicago Board of Election Commissioners 2023 Municipal Runoff Election Results and 2020 U.S. Census.)}"),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)


table_6c

```

