---
title: "Mexican Report"
author: "Citizenship and Civic Participation"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(palmerpenguins)
library("kableExtra") 
library(stringr)
library(knitr)
library(palmerpenguins)
options(tinytex.verbose = TRUE)


usa_data <- read.csv("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/final_Mexican_IL_2000_22.csv") %>% 
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) 
# install.packages("knitr")


<<<<<<< HEAD
=======

>>>>>>> 878e3cc8db24aa0ba803dd993abc3403948e3942
```

\renewcommand{\arraystretch}{1.4}
\clearpage

# 6.Citizenship and Civic Participation

## 6.A:Number and percentages of Mexicans by status

```{r}
# Define df at the top
df <- usa_data %>% 
  select(race_ethnicity, citizen, perwt, year) %>%
  mutate(
    citizenship_status = case_when(
      citizen == 1 ~ "Citizen",
      citizen == 2 ~ "Citizen",
      citizen == 3 ~ "Not a Citizen",
      TRUE ~ "Unknown"  # This includes N/A and any other undefined categories
    )
  )


# 2022
  survey_design <- df %>%
    as_survey_design(weights = perwt)
  
  numerator_2022 <- survey_design %>%
    filter(year == 2022 & citizen == 3) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2022 <- survey_design %>%
     filter(year == 2022)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2022 <- numerator_2022 %>%
    left_join(denominator_2022, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2022)
  
  
# 2012
  
  numerator_2012 <- survey_design %>%
    filter(year == 2012 & citizen == 3) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2012 <- survey_design %>%
     filter(year == 2012)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2012 <- numerator_2012 %>%
    left_join(denominator_2012, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2012)
  
  
  
# 2000
   numerator_2000 <- survey_design %>%
    filter(year == 2000 & citizen == 3) %>%
    group_by(race_ethnicity, citizenship_status) %>%
    summarise(weighted_n = survey_total(vartype = "se"))
  
  denominator_2000 <- survey_design %>%
     filter(year == 2000)%>%
    group_by(race_ethnicity) %>%
    summarise(total_pop = survey_total(vartype = "se"))
  
  df_rates_2000 <- numerator_2000 %>%
    left_join(denominator_2000, by = "race_ethnicity") %>%
    mutate(rate = round(weighted_n / total_pop, 4)*100) %>% 
    mutate(year = 2000)
   
  

# Combine all years
citizenship <- bind_rows(df_rates_2022, df_rates_2012, df_rates_2000)
```



```{r}
 table_6.a1  <- citizenship %>%
  ungroup() %>%
  filter(citizenship_status != "Unknown") %>% 
  select(year, race_ethnicity,  citizenship_status, rate) %>%
  pivot_wider(id_cols = race_ethnicity,   names_from =c(citizenship_status, year) , values_from = rate) %>% 
  mutate(change_non_citizen = round(`Not a Citizen_2022` - `Not a Citizen_2000`, 2)) %>% 
    
    select(race_ethnicity, `Not a Citizen_2000` , `Not a Citizen_2012`,  `Not a Citizen_2022`,change_non_citizen) %>%
  mutate(across(-race_ethnicity, ~ paste0(., "%"))) %>% 
  
  kbl(booktabs = T,
      col.names = c("", "Non citizen Rate", "Non citizen Rate", "Non citizen Rate", "Non citizen Rate"),
      align = c("l",rep("c",4)),
      caption = "Citizenship by Race/Ethnicity in Chicago, 2000-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
 kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:5, width = "6.45em") %>%
  add_header_above(align = c("l", rep("c",4)), c("Race/Ethnicity", "2000" = 1, "2008-2012" = 1, "2018-2022" = 1, "Change from\n2000 to 2018-2022" = 1), 
                   bold = T, font_size =8) %>%
  # row_spec(0, bold = T,
  #          # background = "#f2f0f7",
  #          font_size = 8) %>%

  
  add_footnote(c( "Source: IPUMS-USA database (2000-2022). Tabulations by Great Cities Institute"),
 notation = "none")              

table_6.a1                                                                                                                                                                                                                                                                                                                                                                                                      
```










