---
title: "Mexican Report"
author: "Demographic"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(palmerpenguins)
library("kableExtra") 
library(stringr)
library(knitr)
library(palmerpenguins)
options(tinytex.verbose = TRUE)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(tmap)
library(tmaptools)
library("RColorBrewer") 

# library(OpenStreetMap)
# remotes::install_github('yihui/knitr')
# install.packages("knitr")
# library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("demographic_visual.tex")


##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>% 
  st_transform(crs = 4326)
# mapview(community_shp)
collar_county_border <- st_read("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/cb_2018_us_county_500k/cb_2018_us_county_500k.shp") %>% 
  filter(GEOID %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>% 
  st_transform(crs = 4326) %>% 
  select(GEOID,NAME, geometry) %>% 
  mutate(label = paste0(NAME, " County"))

# Get the current bounding box of the data
bbox_data <- st_bbox(Chicago_boundary_shp)

# Calculate the range of x and y values in degrees
xrange <- bbox_data$xmax - bbox_data$xmin
yrange <- bbox_data$ymax - bbox_data$ymin

# Calculate the center of the bounding box
center_x <- (bbox_data$xmin + bbox_data$xmax) / 2
center_y <- (bbox_data$ymin + bbox_data$ymax) / 2
# Modify the bounding box to fit the desired width while keeping the height the same
bbox_new <- c(center_x - 0.24,
              center_y - 0.23,
              center_x + 0.23,
              center_y + 0.23)

# osm_chicago <- read_osm(bbox_new, 
#                         type = "bing")

bbox_data2 <- st_bbox(collar_county_border)

# Calculate the range of x and y values in degrees
xrange2 <- bbox_data2$xmax - bbox_data2$xmin
yrange2 <- bbox_data2$ymax - bbox_data2$ymin

# Calculate the center of the bounding box
center_x2 <- (bbox_data2$xmin + bbox_data2$xmax) / 2
center_y2 <- (bbox_data2$ymin + bbox_data2$ymax) / 2
# Modify the bounding box to fit the desired width while keeping the height the same
bbox_new_collar <- c(center_x - 0.24,
              center_y - 0.23,
              center_x + 0.23,
              center_y + 0.23)
theme_plots <-
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(color="#969696", linewidth = 1),
        plot.title = element_text(face ="bold", size = 10, hjust = 0.5),
      plot.subtitle = element_text(face ="italic", size = 8, color = "#636363"),
      axis.text = element_text(size = 9),
      axis.title = element_text(face ="bold", size = 9),
      plot.caption = element_text(hjust = 0, size = 8, color = "black"),
      legend.text = element_text(size = 8, color = "#636363"),
      legend.title = element_text(face = "bold", size = 8, color = "#636363")) 


usa_ddi <- read_ipums_micro(read_ipums_ddi("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/usa_00012.xml")) 
# view(usa_ddi)
# colnames(usa_ddi)
# ipums_view(usa_ddi)


collar_data <- usa_ddi %>% 
  select(YEAR, MULTYEAR, RACE, RACED, CITY, PUMA, HISPAN, PERNUM, PERWT,HHWT, SERIAL,NUMPREC, EMPSTAT, IND, OCC, LABFORCE, HHINCOME) %>% 
  clean_names() 


```

\renewcommand{\arraystretch}{1.4}
\clearpage
# Changing Over Time

```{r}

# 17043 DuPage County
# 17089  Kane County
# 17031  Cook County
# 17097 Lake county 
# 17111 McHenry County
# 17197 Will County

######################################## 1980

# chicago_tracts_1980 <- st_read("Data Tables/shp/intersect_census_1980.shp")
# 
# mexican_pop_1980 <- read_nhgis("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/nhgis0044_csv.zip",
#                                file_select = "nhgis0044_csv/nhgis0044_ds104_1980_tract.csv") %>%
# 
#   filter(STATEA == 17) %>%
#   mutate(state_county = paste0(STATEA,COUNTYA)) %>%
#   filter(state_county %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>%
#   select(GISJOIN, YEAR, STATE, COUNTY, state_county,C9F001, C9E002, C7L001) %>%
#   rename("Mexican" = "C9E002",
#          "total_pop" = "C7L001",
#          "total_his" = "C9F001")
# 
# ### Exporting to csv
# ##write.csv(mexican_pop_1980, "Data Tables/mexican_collar_tract_1980.csv")
# 
# ### county 1980
# county_pop_1980 <- mexican_pop_1980 %>%
#   group_by(YEAR, COUNTY, state_county) %>%
#   summarise(Mexican = sum(Mexican, na.rm = TRUE),
#             total_pop = sum(total_pop, na.rm = TRUE),
#             total_his = sum(total_his, na.rm = TRUE))
# 
# 
# 
# chicago_pop_1980 <- mexican_pop_1980 %>%
#   filter(GISJOIN%in%chicago_tracts_1980$GISJOIN) %>%
#   filter(!GISJOIN %in% c("G17003107609", "G17004308400")) %>%  ### exclude the O'Hare
#   group_by(YEAR, COUNTY, state_county) %>%
#   summarise(Mexican = sum(Mexican, na.rm = TRUE),
#             total_pop = sum(total_pop, na.rm = TRUE),
#             total_his = sum(total_his, na.rm = TRUE)) %>%
#   mutate(COUNTY = "Chicago")
# 
# pop_county_chicago_1980 <- rbind(county_pop_1980, chicago_pop_1980)
# 
# write.csv(pop_county_chicago_1980, "Data Tables/pop_county_chicago_1980.csv")


# 
# 
# ####################################################   1990
# chicago_tracts_1990 <- st_read("Data Tables/shp/intersect_census_1990.shp")
# 
# 
# mexican_pop_1990 <- read_nhgis("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/nhgis0044_csv.zip",
#                                file_select = "nhgis0044_csv/nhgis0044_ds120_1990_tract.csv") %>%
# 
#   filter(STATEA == 17) %>%
#   mutate(state_county = paste0(STATEA,COUNTYA)) %>%
#   filter(state_county %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>%
#   select(GISJOIN, YEAR, STATE, COUNTY, state_county, EU1002, ET1001,
#          EU0001) %>%
#   rename("Mexican" = "EU1002",
#          "total_pop" = "ET1001",
#          "total_his" = "EU0001")

### Exporting to csv
##write.csv(mexican_pop_1990, "Data Tables/mexican_collar_tract_1990.csv")
# #
# #
# # county_pop_1990 <- mexican_pop_1990 %>%
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE))
# #
# # chicago_pop_1990 <- mexican_pop_1990 %>%
# #   filter(GISJOIN%in%chicago_tracts_1990$GISJOIN) %>%
# #   filter(!GISJOIN %in% c("G17004308400", "G17003107609")) %>% # parcels in O'hare
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE)) %>%
# #   mutate(COUNTY = "Chicago")
# #
# # pop_county_chicago_1990 <- rbind(county_pop_1990, chicago_pop_1990)
# #
# # write.csv(pop_county_chicago_1990, "Data Tables/pop_county_chicago_1990.csv")
# 
# 
# 
# ####################################################   2000
# 
# chicago_tracts_2000 <- st_read("Data Tables/shp/intersect_census_2000.shp")
# 
# 
# mexican_pop_2000 <- read_nhgis("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/nhgis0044_csv.zip",
#                                file_select = "nhgis0044_csv/nhgis0044_ds146_2000_tract.csv") %>%
# 
#   filter(STATEA == 17) %>%
#   mutate(state_county = paste0(STATEA,COUNTYA)) %>%
#   filter(state_county %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>%
#   select(GISJOIN, STATE, COUNTY, state_county, YEAR, FUH001, FL5001, FMX001) %>%
#   rename("Mexican" = "FUH001",
#          "total_pop" = "FL5001",
#          "total_his" = "FMX001")

### Exporting to csv
##write.csv(mexican_pop_2000, "Data Tables/mexican_collar_tract_2000.csv")
# #
# #
# # county_pop_2000 <- mexican_pop_2000 %>%
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE))
# #
# # chicago_pop_2000 <- mexican_pop_2000 %>%
# #   filter(GISJOIN%in%chicago_tracts_2000$GISJOIN) %>%
# #   filter(!GISJOIN %in% c("G1700430840000", "G1700310760900")) %>%  # parcels in O'hare
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE)) %>%
# #   mutate(COUNTY = "Chicago")
# #
# # pop_county_chicago_2000 <- rbind(county_pop_2000, chicago_pop_2000)
# # #
# # # write.csv(pop_county_chicago_2000, "Data Tables/pop_county_chicago_2000.csv")
# #
# #
# # ####################################################   2010
# #
# chicago_tracts_2010 <- st_read("Data Tables/shp/intersect_census_2010.shp")
# 
# 
# mexican_pop_2010 <- read_nhgis("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/nhgis0044_csv.zip",
#                                file_select = "nhgis0044_csv/nhgis0044_ds173_2010_tract.csv") %>%
# 
#   filter(STATEA == 17) %>%
#   mutate(state_county = paste0(STATEA,COUNTYA)) %>%
#   filter(state_county %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>%
#   select(GISJOIN, STATE, COUNTY,state_county, YEAR, IC2004, IC2001, IC2003 ) %>%
#   rename("Mexican" = "IC2004",
#          "total_pop" = "IC2001",
#         "total_his" = "IC2003")
# #

### Exporting to csv
##write.csv(mexican_pop_2010, "Data Tables/mexican_collar_tract_2010.csv")


# # county_pop_2010 <- mexican_pop_2010 %>%
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE))
# #
# # chicago_pop_2010 <- mexican_pop_2010 %>%
# #   filter(GISJOIN%in%chicago_tracts_2010$GISJOIN) %>%
# #   filter(GISJOIN != "G1700430840000") %>%  # parcels in O'hare
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE)) %>%
# #   mutate(COUNTY = "Chicago")
# #
# # pop_county_chicago_2010 <- rbind(county_pop_2010, chicago_pop_2010)
# #
# # # write.csv(pop_county_chicago_2010, "Data Tables/pop_county_chicago_2010.csv")
# #
# # ####################################################   2020
# #
# chicago_tracts_2020 <- st_read("Data Tables/shp/intersect_census_2020.shp") %>%
#   select(GISJOIN, geometry, GEOID) %>%
#   filter(!GISJOIN %in% c("G1700310980000", "G1700430840000")) %>% # parcels in O'hare
#   st_transform( crs = 4326)
# 
# 
# 
# 
# mexican_pop_18_22 <- get_acs(
#   cache_table = TRUE,
#   geography = "tract",
#   variables = c(Mexican = "B03001_004",
#                 total_pop = "B03001_001",
#                 total_his = "B03001_003"),
#   state = 17,
# 
#   year = 2022
#   # geometry = TRUE
#   ) %>%
# 
#   separate(NAME, c("Census", "COUNTY", "state"), sep = "; ") %>%
# 
#   # rename("Origin" = "variable",
#   #        "Value" = "estimate") %>%
#   pivot_wider(id_cols = c(GEOID, Census, COUNTY, state),
#                names_from = "variable",
#                values_from  = "estimate") %>%
#   mutate(YEAR = "2018-2022") %>%
#   mutate(state_county = substr(GEOID, 1, 5)) %>%
#   filter(state_county %in% c(17043, 17089, 17031, 17097, 17111, 17197))
# 
# 
# ## Exporting to csv
# ## write.csv(mexican_pop_18_22, "Data Tables/mexican_collar_tract_18_22.csv")
# 
# chicago_pop_2020 <- mexican_pop_18_22 %>%
#   filter(GEOID %in% chicago_tracts_2020$GEOID) %>% #
#   group_by(YEAR, COUNTY, state_county) %>%
#   summarise(Mexican = sum(Mexican, na.rm = TRUE),
#             total_pop = sum(total_pop, na.rm = TRUE),
#             total_his = sum(total_his, na.rm = TRUE)) %>%
#   mutate(COUNTY = "Chicago")

#
# #
# #
# #
# # county_pop_2020 <- mexican_pop_18_22 %>%
# #   group_by(YEAR, COUNTY, state_county) %>%
# #   summarise(Mexican = sum(Mexican, na.rm = TRUE),
# #             total_pop = sum(total_pop, na.rm = TRUE),
# #             total_his = sum(total_his, na.rm = TRUE))
# #
# # pop_county_chicago_2020 <- rbind(county_pop_2020, chicago_pop_2020)
# #
# # # write.csv(pop_county_chicago_2020, "Data Tables/pop_county_chicago_2020.csv")
# #
# 
# 
# 
# # # ######### Joining Data
# pop_county_chicago_1980 <- read.csv("Data Tables/pop_county_chicago_1980.csv") %>% mutate(YEAR = as.character(YEAR))
# pop_county_chicago_1990 <- read.csv("Data Tables/pop_county_chicago_1990.csv") %>% mutate(YEAR = as.character(YEAR))
# pop_county_chicago_2000 <- read.csv("Data Tables/pop_county_chicago_2000.csv")%>% mutate(YEAR = as.character(YEAR))
# pop_county_chicago_2010 <- read.csv("Data Tables/pop_county_chicago_2010.csv") %>% mutate(state_county = as.character(state_county))

# # pop_county_chicago_2020 <- read.csv("Data Tables/pop_county_chicago_2020.csv")%>% mutate(state_county = as.character(state_county),
# #                                                                                          )
# #
# #
# pop_county_chicago_1980_2020 <- rbind(pop_county_chicago_1980,
#                                       pop_county_chicago_1990,
#                                       pop_county_chicago_2000,
#                                       pop_county_chicago_2010,
#                                       pop_county_chicago_2020) %>%
#   mutate(COUNTY = case_when(COUNTY == "Cook" ~ "Cook County",
#                             COUNTY == "Kane" ~ "Kane County",
#                             COUNTY == "Lake" ~ "Lake County",
#                             COUNTY == "Dupage" ~ "DuPage County",
#                             COUNTY == "Will" ~ "Will County",
#                             COUNTY == "McHenry" ~ "McHenry County",
#                             TRUE ~ COUNTY)) %>%
#   clean_names() %>%
#   select(-x)
# 
# # write.csv(pop_county_chicago_1980_2020, "Data Tables/pop_county_chicago_1980_2020.csv")


pop_county_chicago_1980_2020 <- read_csv("Data Tables/pop_county_chicago_1980_2020.csv") %>%
  filter(county != "Chicago") %>% 
  select(-`...1`) %>% 
  mutate(year = factor(year, level = c("1980", "1990", "2000", "2010", "2018-2022"))) %>% 
  mutate(county = factor(county, level = c("Cook County", "Kane County", "Lake County", "DuPage County", "Will County", "McHenry County"))) 
  
```


```{r}
county_pop_1980_2020 <- pop_county_chicago_1980_2020 %>% 
  
  mutate(prc_mex_his = 100*round(mexican/total_his, 4),
            prc_mex_total = 100*round(mexican/total_pop, 4)) %>% 
  mutate(prc_mex_his2 = paste0(prc_mex_his, "%"),
         prc_mex_total2 = paste0(prc_mex_total, "%"))

### Table
county_pop_1980_2020_tb <- county_pop_1980_2020 %>% 
  select(county, total_pop, total_his, mexican, prc_mex_his2,prc_mex_total2) %>%
  ## using kable
  kable(booktabs = T,
        col.names = c("Counties", "Total Population", "Total Hispanic/Latino",
                      "Total Mexican", "% Share of Hispanic/Latino", "% Share of Total Population"
                      ),
      align = c("l",rep("c",6)),
      caption = "Mexican Population in Cook County and Collar Counties, Illinois, 1980 to 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                # latex_options = "HOLD_position",
                ) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2:6, width = "8em") %>%
  # add_header_above( c("Race/Ethnicity", "2000" = 2, "2008-2012" = 2, "2018-2022" = 2, "Change from\n2000 to 2018-2022" = 2),
  #                   # background = "#cbc9e2",
  #                   bold = T, font_size =8) %>%
  row_spec(0, bold = T,
           # background = "#f2f0f7",
           font_size = 8) %>%

  pack_rows("1980", 1,6, hline_after = T  ) %>%
  pack_rows("1990", 7, 12, hline_before = T , hline_after = T) %>%
  pack_rows("2000", 13, 18,  hline_before = T , hline_after = T) %>%
  pack_rows("2010", 19, 24,  hline_before = T, hline_after = T ) %>%
  pack_rows("2018-2022", 25, 30, hline_before = T, hline_after = T) %>% 
  footnote(general = "Source: IPUMS NHGIS (1980, 1990, 2000, 2010 Census, and 2018-2022). Tabulations by Great Cities Institute.",
           general_title = "") 
 #  add_footnote(c( "Source: IPUMS NHGIS (1980, 1990, 2000, 2010 Census, and 2018-2022). Tabulations by Great Cities Institute.", "Total Hispanic or Latino for 1980: person of Spanish/Hispanic origin or descent.", "Total Hispanic or Latino for 1990: person of Spanish/Hispanic origin.", "Total Hispanic or Latino for 2000: person of Spanish/Hispanic/Latino origin.", "Total Hispanic or Latino for 2010 and 2020: person of Hispanic, Latino, or Spanish origin."), threeparttable = TRUE,
 # notation = "symbol")

county_pop_1980_2020_tb

```


## hhh

```{r}
county_pop_1980_2020_tb2 <- county_pop_1980_2020 %>% 
  select(year, county, mexican, prc = prc_mex_total) %>%
  pivot_wider( names_from = c(year), values_from = c(mexican, prc)) %>% 
  select(county, mexican_1980, prc_1980, mexican_1990, prc_1990, mexican_2000, prc_2000, mexican_2010, prc_2010, `mexican_2018-2022`, `prc_2018-2022`) %>% 
  
  mutate(change_1980_2020 = `mexican_2018-2022` - mexican_1980,
         prc_change_1980_2020 = `prc_2018-2022` - prc_1980) %>%
  mutate(across(starts_with("prc_"), ~ paste0(.x, "%"))) %>% 
  ## using kable
  kable(booktabs = T,
        col.names = c("" , "Mexican", "Percent", "Mexican", "Percent",
                      "Mexican", "Percent", "Mexican", "Percent",
                      "Mexican", "Percent", "Mexican", "Percent"),
      align = c("l",rep("c",11)),
      caption = "Mexican Population in Cook County and Collar Counties, Illinois, 1980 to 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position",
                ) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2:13, width = "4.8em") %>%
  add_header_above( c("Counties", "1980" = 2, "1990" = 2,  "2000" = 2, "2010" = 2, "2018-2022" = 2, "Change from\n1980 to 2018-2022" = 2),
                    # background = "#cbc9e2",
                    bold = T, font_size =8) %>%
  row_spec(0, bold = T,
           # background = "#f2f0f7",
           font_size = 8) %>%

  footnote(general = "Source: IPUMS NHGIS (1980, 1990, 2000, 2010 Census, and 2018-2022). Tabulations by Great Cities Institute.",
           general_title = "") %>% 
  kableExtra::landscape()
 #  add_footnote(c( "Source: IPUMS NHGIS (1980, 1990, 2000, 2010 Census, and 2018-2022). Tabulations by Great Cities Institute.", "Total Hispanic or Latino for 1980: person of Spanish/Hispanic origin or descent.", "Total Hispanic or Latino for 1990: person of Spanish/Hispanic origin.", "Total Hispanic or Latino for 2000: person of Spanish/Hispanic/Latino origin.", "Total Hispanic or Latino for 2010 and 2020: person of Hispanic, Latino, or Spanish origin."), threeparttable = TRUE,
 # notation = "symbol")

county_pop_1980_2020_tb2
```

### Graph

```{r}
# line_chart <- county_pop_1980_2020 %>% 
#   ggplot() +
#   geom_line(data = filter(county_pop_1980_2020, county!= "Cook County") ,
#             aes(x = year, y = mexican, group = county),
#             color = "#636363",
#             linewidth =1 ) +
#   # geom_line(data = filter(county_pop_1980_2020, county == "Cook County") ,
#   #           aes(x = year, y = mexican, group = county),
#   #           color = "#C91835",
#   #           linewidth =1 ) +
#   # geom_point(data = filter(county_pop_1980_2020, county!= "Cook County") ,
#   #           aes(x = year, y = mexican, group = county),
#   #           shape = 21,
#   #           color = "#636363",
#   #           size = 2 ) +
#   theme_plots


```



```{r}

# 
lollipop_chart <- county_pop_1980_2020 %>% 
  # filter(county != "Cook County") %>% 
  ggplot() +

  geom_line(aes(y = county, x = mexican, group = county, color = year),
            color = "#636363",
            linewidth =1 ) +
  geom_point(aes(y = county, x = mexican, group = county, color = year),
            shape = 20,
            # color = "#636363",
            size = 4
            ) +
  # geom_line(data = filter(county_pop_1980_2020, county == "Cook County") ,
  #           aes(x = year, y = mexican, group = county),
  #           color = "#C91835",
  #           linewidth =1 ) +
  # geom_point(data = filter(county_pop_1980_2020, county!= "Cook County") ,
  #           aes(x = year, y = mexican, group = county),
  #           shape = 21,
  #           color = "#636363",
  #           size = 2 ) +
  theme_plots

lollipop_chart

```


### Maps

```{r fig.height=11, fig.width=8}


county_pop_1980_2020_2 = county_pop_1980_2020 %>% mutate(state_county = as.character(state_county))

Collar_county_pop_shp <- 
  left_join(collar_county_border , county_pop_1980_2020_2, by = join_by("GEOID" == "state_county"))


collar_mexican_map_2022 <-

  tm_shape(Collar_county_pop_shp
           # , bbox = bbox_new
           ) +
  tm_borders(col = "#6c757d",
             alpha = 1,
             lwd = 1) +
  tm_symbols(shape = 20,
             size = "prc_mex_total",
             alpha = 0.5,
             scale = 11,
             "#C91835",
             legend.size.show = FALSE)+
  tm_polygons(
    col = "mexican",
              style = "jenks",
              border.col = "#ced4da",
              palette="Blues",
              alpha = 0.7,
              n = 5,
              title = "Mexican Population",
              lwd = 0.3) +
  tm_borders(col = "#6c757d",
             alpha = 1,
             lwd = 1) +
    tm_facets(by = "year",
              ncol = 2) +
  tm_text("prc_mex_total2" , size = 1.5, alpha = 1, fontface="bold", fontfamily = "sans", col = "black") +
    tm_layout( frame = TRUE,
            legend.width = 1.5,
            legend.title.size = .9,
            legend.text.size = 0.8,
            legend.title.fontface = "bold",
            # legend.position = c("right", "bottom"),
            legend.position = c(-0.6, 0.12)
    
            )       # manually position legend) +
  


collar_mexican_map_2022

 
```


## By Year


```{r, include=FALSE}
mexican_pop_1980 <- read.csv("Data Tables/mexican_collar_tract_1980.csv")
mexican_shp_1980 <- st_read("Data Tables/shp/MSA_dots_1980_origin_50.shp") %>% 
  filter(Origin == "Mexican") %>% 
  filter(GISJOIN %in% mexican_pop_1980$GISJOIN) %>% 
  st_transform(crs = 4326)
```

```{r fig.height=11, fig.width=8}
# 
# 
# bbox_new_collar <- c(center_x - 1.25,
#               center_y - 0.7,
#               center_x + 0.45,
#               center_y + 0.8)
# 
# 
# 
# collar_county_1980 <-
#   
#   tm_shape(Collar_county_pop_shp %>% filter(year == "1980"), bbox = bbox_new_collar) +
#   tm_polygons(col = "prc_mex_total",
#               palette = "YlOrRd",
#               style = "jenks",
#               # border.col = "#ced4da",
#               # palette="Blues",
#               alpha = 0.4,
#               n = 5,
#               title = "Percentage",
#               lwd = 0.3)+
# 
#   tm_shape(mexican_shp_1980, bbox = bbox_new_collar) +
#   tm_dots(col = "Origin",
#           palette = "#1565c0",
#           size = 0.025,
#           legend.show = FALSE,
#           alpha = 0.3) +
# 
#   tm_shape(collar_county_border) +
#   tm_borders(col = "#6c757d",
#              alpha = 1,
#              lwd = 3)+
#   tm_text("label" , size = 0.6, alpha = 0.9, fontface="bold", fontfamily = "sans") +
# 
#   # tm_shape(Chicago_boundary_shp) +
#   # tm_borders(col = "#343a40",
#   #            alpha = 0.7,
#   #            lwd = 2.5) +
# 
#   tm_layout( frame = TRUE,
#              # main.title.position = c("left", "top"),
#              # main.title = "Density of Hispanic or Latino Population by their Origins in Chicago, 2010",
#              # main.title.size = 1.2,
#             legend.outside = FALSE,
#             # legend.width = 1.5,
#             legend.title.size = .9,
#             legend.text.size = 0.8,
#             legend.title.fontface = "bold",
#             # legend.position = c("left", "bottom"),
#             legend.position = c(0.03, 0.12),
#             # legend.bg.color = "white",
#             # legend.bg.alpha = .3
#             ) +       # manually position legend) +
#   tm_credits("Data source:\nIPUMS NHGIS (1980 Census)\nMap Generated by:\nThe Great Cities Institute",
#              fontface = "bold",
#              position = c("left","bottom"), size = 0.8)+
# 
#   tm_credits("Distribution of Mexican Population in Cook County and\nCollar Counties, Illinois, 1980",
#              fontface = "bold",
#              position = c("left","top"), size = 1.25)+
# 
# 
#   tm_add_legend("symbol",
#                 labels = "Mexican",
#                 col = "#1565c0",
#                 size = 0.6,
#                 title = "1 dot = 50 People") +
# 
#   tm_add_legend("line",
#                 labels = c("Chicago Border", "Community Area Border"),
#                 col = c("#343a40", "#6c757d"),
#                 lwd = c(2.5, 2),
#                 title = "Border Types",
#                 size = 0.8) +
# 
#   # tm_credits("1 dot = 20 People",
#   #            position = c(0.03, 0.32), size = 0.8, fontface = "bold") +
#   tm_compass(position = c("right", "bottom"), size = 1) +
#   tm_scale_bar(position = c("right", "bottom"), width = 0.15)
# 
# collar_county_1980


```


### Comparing Cook County to Counties with the Largest Mexican Population

```{r}




```

