---
title: "Mexican Report"
author: "Demographic"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


```{r}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(tinytex)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(tmap)
library("kableExtra") 
library(tmaptools)
library("RColorBrewer") 
# library(OpenStreetMap)
# remotes::install_github('yihui/knitr')
# install.packages("knitr")
# library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("demographic_visual.tex")

##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>% 
  st_transform(crs = 4326)
# mapview(community_shp)


### usa data

# Read Data

usa_data <- read.csv("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/final_Mexican_IL_2000_22.csv") %>% 
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)")))
```



\renewcommand{\arraystretch}{1.4}


\clearpage

# Demographic


## 1B(1): Population Pyramid and Percentage of Mexican population, 2018-2022:

```{r}
# analysis

# filter for year 2022

data_chi_2018_22 <- usa_data %>% filter(year == 2022)

# 1B: Population pyramid of the percentage of Mexican population by age group compared to the rest of the population in Chicago and median age in Chicago (Data source: 2018-2022 ACS data)

df <-  data_chi_2018_22 %>%
  mutate(
    age_group = case_when(
      age < 20 ~ "Young (0-19)",
      age >= 20 & age < 40 ~ "Young Adults (20-39)",
      age >= 40 & age < 60 ~ "Middle-aged (40-59)",
      age >= 60 & age < 80 ~ "Older Adults (60-79)",
      age >= 80 ~ "Elderly (80+)"
    )
  )
# Create survey design object
survey_design <- df %>%
  as_survey_design(weights = perwt)


# Calculate weighted population counts by age group and ethnicity

# Calculate weighted population by ethnicity and age group
pop_pyramid <- df %>%
  as_survey_design(weights = perwt) %>% 
  survey_count(race_ethnicity, age_group, name="total_weighted_count")  %>%
  group_by(race_ethnicity) %>%
  mutate(total_weighted_percentage = total_weighted_count / sum(total_weighted_count) * 100,
         total_weighted_percentage  = paste0(round(total_weighted_percentage, 1), "%")) 



# get median age

weighted_age  <- df %>%
  group_by(race_ethnicity) %>%
  summarize(
    weighted_age = matrixStats::weightedMedian(age, perwt)
  ) 



# combined

df_final  <- pop_pyramid %>% left_join(weighted_age)

```








```{r}
# visual

table_1b.1 <- df_final  %>% pivot_wider(id_cols = c("race_ethnicity"), names_from = age_group, values_from = c("total_weighted_count", "total_weighted_percentage")) %>% select(race_ethnicity, 
                                                                                                                                                'total_weighted_count_Young (0-19)', 'total_weighted_percentage_Young (0-19)',
                                                                                                                                                 'total_weighted_count_Young Adults (20-39)', 'total_weighted_percentage_Young Adults (20-39)',
                                                                                                                                                 'total_weighted_count_Middle-aged (40-59)', 'total_weighted_percentage_Middle-aged (40-59)',
                                                                                                                                                 'total_weighted_count_Older Adults (60-79)', 'total_weighted_percentage_Older Adults (60-79)',
                                                                                                                                                 'total_weighted_count_Elderly (80+)', 'total_weighted_percentage_Elderly (80+)')   %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
      col.names = c("", "Number", "Percent" , "Number", "Percent", "Number", "Percent", "Number", "Percent", "Number", "Percent"),
      align = c("l",rep("c",10)),
      caption = "Population Pyramid of the Mexican Population, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2:11, width = "2.58em") %>%  

 add_header_above( align = c("l", rep("c",2)), c("Race/Ethnicity", "Young(0-19)" = 2, "Young Adults(0-19)" = 2, "Middle Aged (40-59)" = 2, "Older Adults (60-79)" = 2, "Elderly(80+)" = 2),
                    # background = "#cbc9e2", 
                    bold = T, font_size =8) %>% 

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   


table_1b.1
```


## 1B(2): Median Age of Mexican population, 2018-2022:

```{r}
# analysis

# filter for year 2022

data_chi_2018_22 <- usa_data %>% filter(year == 2022)

# 1B: Population pyramid of the percentage of Mexican population by age group compared to the rest of the population in Chicago and median age in Chicago (Data source: 2018-2022 ACS data)

df <-  data_chi_2018_22 %>%
  mutate(
    age_group = case_when(
      age < 20 ~ "Young (0-19)",
      age >= 20 & age < 40 ~ "Young Adults (20-39)",
      age >= 40 & age < 60 ~ "Middle-aged (40-59)",
      age >= 60 & age < 80 ~ "Older Adults (60-79)",
      age >= 80 ~ "Elderly (80+)"
    )
  )
# Create survey design object
survey_design <- df %>%
  as_survey_design(weights = perwt)


# Calculate weighted population counts by age group and ethnicity

# Calculate weighted population by ethnicity and age group
pop_pyramid <- df %>%
  as_survey_design(weights = perwt) %>% 
  survey_count(race_ethnicity, age_group, name="total_weighted_count")  %>%
  group_by(race_ethnicity) %>%
  mutate(total_weighted_percentage = total_weighted_count / sum(total_weighted_count) * 100,
         total_weighted_percentage  = paste0(round(total_weighted_percentage, 1), "%")) 



# get median age

weighted_age  <- df %>%
  group_by(race_ethnicity) %>%
  summarize(
    weighted_age = matrixStats::weightedMedian(age, perwt)
  ) 



# combined

df_final  <- pop_pyramid %>% left_join(weighted_age)
```


```{r}
# visuals
# visuals

table_1b.2 <- weighted_age  %>% select(race_ethnicity, weighted_age) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
       col.names = c("Race/Ethnicity", "Number"),
      align = c("l",rep("c",1)),
      caption = "Median Age of the Mexican Population, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2, width = "25.8em") %>%  

  row_spec(0, bold = T,
             #background = "#f2f0f7",
            font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_1b.2


```



## 1C: Average Family Size of the Mexican Population, 2018-2022:

```{r}
# analysis

# filter for year 2022

data_chi_2018_22 <- usa_data %>% filter(year == 2022)


# Filter for the head of household 
data_head_of_household <- data_chi_2018_22 %>%
  filter(pernum == 1)

# 1C Average family size of the Mexican population compared to, other Latinos, Black and White populations in Chicago

# Calculate average family size

# Define the survey design using srvyr with only weights
survey_design <- data_head_of_household %>%
  as_survey_design(weights = hhwt)

# Calculate the weighted average family size by group
avg_family_size <- survey_design %>%
  group_by(race_ethnicity) %>%
  summarize(
        avg_family_size = survey_mean(famsize, vartype = "se", na.rm = TRUE)
  ) %>%  mutate(
    avg_family_size = round(avg_family_size)
  )




```

```{r}
# visuals

table_1c <- avg_family_size %>% select(race_ethnicity, avg_family_size) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
       col.names = c("Race/Ethnicity", "Number"),
      align = c("l",rep("c",1)),
      caption = "Average Family Size of the Mexican Population, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2, width = "25.8em") %>%  

  row_spec(0, bold = T,
             #background = "#f2f0f7",
            font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_1c


```





## 1D(1): Income Levels, 2018-2022:

```{r}
# analysis
# filter for 2022

data_chi_2018_22 <- usa_data %>% filter(year == 2022)

# 1D Income Levels and poverty rates for Mexicans, other Latinos, Black and White Populations in Chicago.

# Filter the data to remove negative and extreme values
filtered_data <- data_chi_2018_22 %>%
  filter(hhincome >= 0 & hhincome < 9999999, pernum == 1)
  
# Define the survey design using srvyr with only weights
survey_design <- filtered_data  %>%
  as_survey_design(weights = hhwt)

# Calculate the weighted average household income by group
weighted_avg_income <- survey_design %>% filter(pernum == 1) %>%
  group_by(race_ethnicity) %>%
  summarize(
    avg_hhincome = survey_mean(hhincome, vartype = "se", na.rm = TRUE)
  )


# weighted median: 

weighted_median_income <- data_chi_2018_22 %>%  filter(pernum == 1) %>%
  group_by(race_ethnicity) %>%
  summarize(
    weighted_median_hhincome = matrixStats::weightedMedian(hhincome,  weights = hhwt)
  ) %>%
  ungroup()


# final df with income levels
income_levels <- weighted_avg_income %>% left_join(weighted_median_income)  %>%
  mutate(
    avg_hhincome = paste0("$", format(avg_hhincome, big.mark = ",", scientific = FALSE)),
    weighted_median_hhincome = paste0("$", format(weighted_median_hhincome, big.mark = ",", scientific = FALSE))
  )


```


```{r}
# visuals
# visual



table_1d.1 <- income_levels %>% select(race_ethnicity, avg_hhincome, weighted_median_hhincome) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
      col.names = c("Race/Ethnicity", "Average Household Income", "Median Household Income"),
      align = c("l",rep("c",2)),
      caption = "Average and Weighted Median Income of Mexican Population, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2:3, width = "12.9em") %>%  

  row_spec(0, bold = T,
             #background = "#f2f0f7",
            font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_1d.1
```


## 1D(2): Poverty Rates, 2018-2022:

```{r}
# analysis

# poverty


# Define the survey design using srvyr with only weights
survey_design2 <- data_chi_2018_22  %>%
  as_survey_design(weights = perwt)
  

  
# Calculate poverty rates by group

# Calculate total weighted count by race_category and ethnicity
total_weighted_pop_count <- survey_design2 %>%
  group_by(race_ethnicity) %>%
  summarise(total_weighted_pop_count = survey_total())

# Calculate total weighted count in poverty by race_category and ethnicity
total_weighted_poverty_count <- survey_design2 %>%
  filter(poverty <= 1) %>%
  group_by(race_ethnicity) %>%
  summarise(total_weighted_poverty_count = survey_total())

# Combine total counts and poverty counts
combined <- left_join(total_weighted_pop_count, total_weighted_poverty_count)


poverty_rate <- combined %>% mutate(poverty_rate = (total_weighted_poverty_count/total_weighted_pop_count)*100,
                                    poverty_rate   = paste0(round(poverty_rate, 1), "%")) 

```


```{r}
# visuals


table_1d.2 <- poverty_rate  %>% select(race_ethnicity, total_weighted_poverty_count, poverty_rate) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
      col.names = c("Race/Ethnicity", "Number", "Percent"),
      align = c("l",rep("c",2)),
      caption = "Mexican Population at or Below 1% Poverty Threshold, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2:3, width = "12.9em") %>%  

  row_spec(0, bold = T,
             #background = "#f2f0f7",
            font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_1d.2
```

## 1E: Population by Mexican indigenous groups, 2018-2022:

```{r}
# analysis

# filter for 2022

data_chi_2018_22 <- usa_data %>% filter(year == 2022)


# check ipums labels

# Ensure data_chi_2018_22 is loaded

# make tribe a character
data_chi_2018_22$tribe_f <- as.character(data_chi_2018_22$tribe_f)


# create native groups by collapsing categories

data_recoded <- data_chi_2018_22  %>% mutate(
    tribe_label_collapsed = case_when(
      tribe_f %in% c("Not applicable or blank", "American Indian, tribe not specified", "American Indian and Alaska Native, not specified",
                         "American Indian and Alaska Native, tribe not elsewhere classified", 
                         "American Indian, tribe not elsewhere classified", "All other specified American Indian tribe combinations") ~ "Unspecified/Other",
      TRUE ~ tribe_f
    )
  )
 

# Population by Mexican indigenous groups by Public Use Microdata Areas (PUMAs) in Chicago.  

# Filter data for Mexican who identify as AIAN and select relevant columns
mexican_indigenous <- data_recoded %>%
  filter(hispan == 1 & race == 3) %>%
  select(puma, tribe_label_collapsed, perwt)

# Create survey design with weights
survey_design <- mexican_indigenous %>%
  as_survey_design(weights = perwt)

# Count the number of individuals by indigenous tribe within each PUMA
tribe_count <- survey_design %>%
  survey_count(tribe_label_collapsed, name = "total_weighted_count")

# round 
tribe_count  <- tribe_count %>% mutate(
  total_weighted_count_se = round(total_weighted_count_se, 1)
)
```


```{r}
# visuals


table_1e <- tribe_count %>% select(tribe_label_collapsed, total_weighted_count) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
      col.names = c("Race/Ethnicity", "Number"),
      align = c("l",rep("c",1)),
      caption = "Population by Mexican indigenous groups, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2, width = "25.8em") %>%  

  row_spec(0, bold = T,
             #background = "#f2f0f7",
            font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_1e
```

