---
title: "Mexican Report"
author: "Demographic"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(tinytex)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(tmap)
library("kableExtra") 
library(tmaptools)
library("RColorBrewer") 
# library(OpenStreetMap)
# remotes::install_github('yihui/knitr')
# install.packages("knitr")
library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("demographic_visual.tex")


##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>% 
  st_transform(crs = 4326)
# mapview(community_shp)

# Get the current bounding box of the data
bbox_data <- st_bbox(Chicago_boundary_shp)

# Calculate the range of x and y values in degrees
xrange <- bbox_data$xmax - bbox_data$xmin
yrange <- bbox_data$ymax - bbox_data$ymin

# Calculate the center of the bounding box
center_x <- (bbox_data$xmin + bbox_data$xmax) / 2
center_y <- (bbox_data$ymin + bbox_data$ymax) / 2
# Modify the bounding box to fit the desired width while keeping the height the same
bbox_new <- c(center_x - 0.24,
              center_y - 0.23,
              center_x + 0.23,
              center_y + 0.23)

# osm_chicago <- read_osm(bbox_new, 
#                         type = "bing")


comm_2022 <- st_read("Data Tables/shp/comm_pop_chi_2022.shp")
tract_2022 <- st_read("Data Tables/shp/tract_pop_chi_2022.shp")

```

\renewcommand{\arraystretch}{1.4}
\clearpage

# Demographic

## 1A: Mexican population, concentration by census tract and community area along with historic trends in Chicago (Data source: 2018-2022, 2008-2012 ACS and 2000 census). 

### Percentage of the Mexican Population in Chicago\nby Census Tracts, 2018-2022

```{r fig.height=11, fig.width=8}



census_mexican_map_2022 <-

  tm_shape(tract_2022, bbox = bbox_new) +
  tm_polygons(
    col = "prc",
              style = "jenks",
              border.col = "#ced4da",
              palette="Blues",
              alpha = 0.7,
              n = 5,
              title = "Percentage of the Mexican Population",
              lwd = 0.3) +
  tm_shape(comm_2022) +
  tm_borders(col = "#6c757d",
             alpha = 1,
             lwd = 1)+
  
  # tm_shape(comm_2022 %>% filter(prc>=50)) +
  # tm_borders(col = "#9b2226",
  #            alpha = 1,
  #            lwd = 2)+
  tm_text("lable" , size = 0.6, alpha = 0.7, fontface="bold", fontfamily = "sans")+

  tm_shape(Chicago_boundary_shp) +
  tm_borders(col = "#343a40",
             alpha = 1,
             lwd = 2.5) +

  tm_layout( frame = TRUE,
             # main.title.position = c("left", "top"),
             # main.title = "Density of Hispanic or Latino Population by their Origins in Chicago, 2010",
             # main.title.size = 1.2,
            legend.outside = FALSE,
            legend.width = 1.5,
            legend.title.size = .9,
            legend.text.size = 0.8,
            legend.title.fontface = "bold",
            # legend.position = c("left", "bottom"),
            legend.position = c(0.03, 0.12),
            legend.bg.color = "white",
            legend.bg.alpha = .3)       # manually position legend) +
  
  # tm_credits("Data source:\n5-year ACS (2022)\nMap Generated by:The Great Cities Institute",
  #            fontface = "bold",
  #            position = c("left","bottom"), size = 0.8)+
  # 
  # 
  # tm_credits("Percentage of the Mexican Population in Chicago by Census Tracts, 2018-2022",
  #            fontface = "bold",
  #            position = c("left","top"), size = 1.25)+
  # 
  # 
  # tm_add_legend("line",
  #               labels = c("Chicago Border", "Community Area Border"),
  #               col = c("#343a40","#6c757d"),
  #               lwd = c(2.5, 2),
  #               title = "Border Types",
  #               size = 0.8) +
  # 
  # # tm_credits("1 dot = 20 People",
  # #            position = c(0.03, 0.32), size = 0.8, fontface = "bold") +
  # tm_compass(position = c("right", "bottom"), size = 1) +
  # tm_scale_bar(position = c("right", "bottom"), width = 0.15)

census_mexican_map_2022


```


<!-- ### the Mexican Population in Chicago\nby Census Tracts, 2018-2022 -->

<!-- ```{r fig.height=11, fig.width=8} -->

<!-- census_mexican_pop_map_2022 <- -->

<!--   tm_shape(tract_2022, bbox = bbox_new) + -->
<!--   tm_polygons( -->
<!--     col = "ttl_mxc", -->
<!--               style = "jenks", -->
<!--               border.col = "#ced4da", -->
<!--               palette="Blues", -->
<!--               alpha = 0.7, -->
<!--               n = 5, -->
<!--               title = "Mexican Population", -->
<!--               lwd = 0.3) + -->
<!--   tm_shape(comm_2022) + -->
<!--   tm_borders(col = "#6c757d", -->
<!--              alpha = 1, -->
<!--              lwd = 1) + -->

<!--   # tm_shape(comm_2022 %>% filter(prc>=50)) + -->
<!--   # tm_borders(col = "#9b2226", -->
<!--   #            alpha = 1, -->
<!--   #            lwd = 2)+ -->
<!--   tm_text("lable" , size = 0.6, alpha = 0.7, fontface="bold", fontfamily = "sans")+ -->

<!--   tm_shape(Chicago_boundary_shp) + -->
<!--   tm_borders(col = "#343a40", -->
<!--              alpha = 1, -->
<!--              lwd = 2.5) + -->

<!--   tm_layout( frame = TRUE, -->
<!--              # main.title.position = c("left", "top"), -->
<!--              # main.title = "Density of Hispanic or Latino Population by their Origins in Chicago, 2010", -->
<!--              # main.title.size = 1.2, -->
<!--             legend.outside = FALSE, -->
<!--             legend.width = 1.5, -->
<!--             legend.title.size = .9, -->
<!--             legend.text.size = 0.8, -->
<!--             legend.title.fontface = "bold", -->
<!--             # legend.position = c("left", "bottom"), -->
<!--             legend.position = c(0.03, 0.12), -->
<!--             legend.bg.color = "white", -->
<!--             legend.bg.alpha = .3) +       # manually position legend) + -->

<!--   tm_credits("Data source:\n5-year ACS (2022)\nMap Generated by:The Great Cities Institute", -->
<!--              fontface = "bold", -->
<!--              position = c("left","bottom"), size = 0.8)+ -->


<!--   tm_credits("Mexican Population in Chicago by Census Tracts, 2018-2022", -->
<!--              fontface = "bold", -->
<!--              position = c("left","top"), size = 1.25)+ -->


<!--   tm_add_legend("line", -->
<!--                 labels = c("Chicago Border", "Community Area Border"), -->
<!--                 col = c("#343a40","#6c757d"), -->
<!--                 lwd = c(2.5, 2), -->
<!--                 title = "Border Types", -->
<!--                 size = 0.8) + -->

<!--   # tm_credits("1 dot = 20 People", -->
<!--   #            position = c(0.03, 0.32), size = 0.8, fontface = "bold") + -->
<!--   tm_compass(position = c("right", "bottom"), size = 1) + -->
<!--   tm_scale_bar(position = c("right", "bottom"), width = 0.15) -->

<!-- census_mexican_pop_map_2022 -->


<!-- ``` -->


