---
title: "Housing"
author: "Employment and Business"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library("kableExtra") 

```
\renewcommand{\arraystretch}{1.4}
\clearpage


```{r}
usa_ddi <- read_ipums_micro(read_ipums_ddi("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/usa_00010.xml")) 
# view(usa_ddi)
# colnames(usa_ddi)
# ipums_view(usa_ddi)


Business_ddi <- usa_ddi %>% 
  select(YEAR, MULTYEAR, RACE, RACED, CITY, PUMA, HISPAN, PERNUM, PERWT,HHWT, SERIAL,NUMPREC, EMPSTAT, IND, OCC, LABFORCE, HHINCOME) %>% 
  clean_names() 

# ipums_val_labels(Business_ddi$ind)
# ipums_val_labels(housing_ddi$hispan)

```

# 5A.1: Unemployment Rate

```{r}

unemployment = Business_ddi %>% 
  filter( city == 1190, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not?
  mutate(race_f = as_factor(race),
         hispan_f = as_factor(hispan), 
         laborforce = as_factor(labforce), 
         employment = as_factor(empstat)) %>% 
  
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>% 
  
  as_survey_design(weights = perwt) %>% 
  survey_count(race_ethnicity, employment, laborforce,  name="count") %>% 
  filter(laborforce == "Yes, in the labor force") %>% 
  group_by(race_ethnicity) %>% 
  mutate(in_laborforce = sum(count)) %>% 
  filter(employment == "Unemployed") %>% 
  mutate(unemployment_rate = 100*round(count/in_laborforce, 4),
         prc2 = paste0(unemployment_rate, "%"))
  



table_5.a1 <- unemployment %>%
  select(race_ethnicity,  in_laborforce, count, prc2) %>%

  # using kable

  kbl(booktabs = T,
      col.names = c("Race/Ethnicity",  "In the Labor Force" ,"Unemployed", "Percent"),
      align = c("l",rep("c",3)),
      caption = "Unemployment Rate by Race/Ethnicity in Chicago, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
 kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:4, width = "8.6em") %>% 
  # add_header_above(align = c("l", rep("c",3)), c("Race/Ethnicity", "More than 30%" = 2, "More than 50%" = 2),
  #                   # background = "#cbc9e2",
  #                   bold = T, font_size =8) %>%
  row_spec(0, bold = T,
           # background = "#f2f0f7",
           font_size = 8) %>%

  
  add_footnote(c( "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute"),
 notation = "none")

table_5.a1

```


<!-- # 5A.2: Numbers and percentages of Mexicans employed, by industry -->


<!-- ```{r} -->

<!-- industry = Business_ddi %>%  -->
<!--   filter( city == 1190, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not? -->
<!--   mutate(race_f = as_factor(race), -->
<!--          hispan_f = as_factor(hispan),  -->
<!--          laborforce = as_factor(labforce),  -->
<!--          employment = as_factor(empstat)) %>%  -->

<!--   mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)", -->
<!--                                     hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)", -->
<!--                                     hispan %in% c(2,3,4) ~ "Other Latinos", -->
<!--                                     hispan ==1 ~ "Mexican",  -->
<!--                                     hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)", -->
<!--                                     TRUE ~ NA_character_)) %>%  -->
<!--   mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>%  -->

<!--   mutate(industry = case_when(ind %in% c(0170:0490)  ~ "Agriculture, Forestry, Fishing, and Hunting, and Mining", -->
<!--                               ind == 0770  ~ "Construction", -->
<!--                               ind %in% c(1070:3990)  ~ "Manufacturing", -->
<!--                               ind %in% c(4070:4590)  ~ "Wholesale Trade", -->
<!--                               ind %in% c(4670:5790)  ~ "Retail Trade", -->
<!--                               ind %in% c(6070:6390, 0570:0690) ~ "Transportation and Warehousing, and Utilities", -->
<!--                               ind %in% c(6470:6780)  ~ "Information", -->
<!--                               ind %in% c(6870:7190)  ~ "Finance and Insurance, and Real Estate, and Rental and Leasing", -->
<!--                               ind %in% c(7270:7790)  ~ "Professional, Scientific, and Management, and Administrative, and Waste Management Services", -->
<!--                               ind %in% c(7860:8470)  ~ "Educational Services, and Health Care and Social Assistance", -->
<!--                               ind %in% c(8561:8690)  ~ "Arts, Entertainment, and Recreation, and Accommodation and Food Services", -->
<!--                               ind %in% c(8770:9290)  ~ "Other Services, Except Public Administration", -->
<!--                               ind %in% c(9370:9590)  ~ "Public Administration", -->
<!--                               ind %in% c(9670:9870)  ~ "Military", -->
<!--                               ind == 9920  ~ "Unemployed, last worked 5 years ago or earlier or never worked", -->

<!--                                     TRUE ~ NA_character_)) %>%  -->

<!--   as_survey_design(weights = perwt) %>%  -->
<!--   survey_count(race_ethnicity, industry, employment, name="count") %>%  -->
<!--   filter(employment == "Employed") %>%  -->
<!--   group_by(race_ethnicity) %>%  -->
<!--   mutate(total_employed = sum(count, na.rm = T)) %>%  -->
<!--   mutate(prc = 100* round(count/total_employed, 4), -->
<!--          prc2 = paste0(prc,"%")) %>%  -->
<!--   ungroup() -->


<!-- table_5a.1 <-  industry %>%  -->
<!--   select(industry, count,  prc2) %>%  -->

<!--    # using kable  -->

<!--   kbl(booktabs = T, -->
<!--       col.names = c("Industry", "Number", "Percent"  ), -->
<!--       align = c("l",rep("c",2)), -->
<!--       caption = "Number and Percentage of Households Living in Crowded Housing by Race/Ethnicity in Chicago, 2018-2022", -->
<!--       format.args = list(big.mark = ","), -->
<!--       linesep = "") %>%  -->
<!--   kable_classic(full_width = T,   -->
<!--                 font_size = 8, -->
<!--                 html_font = "Arial", -->
<!--                 position = "center", -->
<!--                 latex_options = "HOLD_position") %>%  -->
<!--   # column_spec(1, width = "10em") %>% -->
<!--   # column_spec(2:8, width = "3.8em") %>% -->
<!--   # add_header_above( c("Race/Ethnicity", "2000" = 2, "2008-2012" = 2, "2018-2022" = 2, "Change from\n2000 to 2018-2022" = 2), -->
<!--   #                   # background = "#cbc9e2", -->
<!--   #                   bold = T, font_size =8) %>% -->

<!--   pack_rows("Black (non-Hispanic or Latino)", 1, 14, label_row_css = "background-color: #f7f7f7;") %>%  -->
<!--   pack_rows("Other Latinos", 15, 28, label_row_css = "background-color: #f7f7f7;") %>%  -->
<!--   pack_rows("Mexican", 29, 42, label_row_css = "background-color: #f7f7f7;") %>%  -->
<!--   pack_rows("Other (non-Hispanic or Latino)", 43, 56, label_row_css = "background-color: #f7f7f7;") %>%  -->
<!--   pack_rows("White (non-Hispanic or Latino)", 57, 70, label_row_css = "background-color: #f7f7f7;") %>%  -->
<!--   row_spec(0, bold = T, -->
<!--            # background = "#f2f0f7", -->
<!--            font_size = 8) %>% -->
<!--   add_footnote(c( "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute"), -->
<!--  notation = "none") -->

<!--   footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute. Housing is defined as overcrowded if more than 1 person in the room. -->
<!-- ", -->
<!--            general_title = "")   -->

<!-- table_5a.1 -->

<!-- ``` -->



<!-- ```{r} -->

<!-- ``` -->











