---
title: "Mexican Report"
author: "Housing"
date: "Great Cities Institute"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(tinytex)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library("kableExtra") 
# install.packages("knitr")
# library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("Housing_Visual.tex")
```

\renewcommand{\arraystretch}{1.4}
\clearpage

```{r}
usa_ddi <- read_ipums_micro(read_ipums_ddi("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/usa_00006.xml")) 
# view(usa_ddi)
# colnames(usa_ddi)
# ipums_view(usa_ddi)


# revised_extract <- revise_extract_micro(
#     old_extract,
#     samples = "us2017a",
#     vars = "EDUC"
# )
# 
# revised_extract <- remove_from_extract(
#     revised_extract,
#     vars = "RACE"
# )
housing_ddi <- usa_ddi %>% 
  select(YEAR, MULTYEAR, RACE, RACED, CITY, PUMA, HISPAN, OWNERSHP, OWNERSHPD, PERNUM, PERWT,HHWT, SERIAL, ROOMS, NUMPREC, OWNCOST, RENTGRS, HHINCOME) %>% 
  clean_names() 

# ipums_val_labels(housing_ddi$hi)
# ipums_val_labels(housing_ddi$hispan)


```


```{r}

homeownership = housing_ddi %>% 
  filter( city == 1190, pernum == 1) %>%  #### dont forget to filter PUMA 
  mutate(race_f = as_factor(race),
         hispan_f = as_factor(hispan),
         ownershp_f = as_factor(ownershp)) %>% 
  
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>% 
  
  as_survey_design(weights = hhwt) %>% 
  
  survey_count(year, race_ethnicity, ownershp_f, name="count") %>% 
  
  filter(!is.na(race_ethnicity)) %>% 
  
  group_by(year, race_ethnicity) %>% 
  mutate(total = sum(count),
         per = 100*round(count/total, 4),
         per2 = paste0(per,"%"))
  
 # #### Export 
#  
  
  
```

# Housing

## 3.A: Rates of home ownership and rental housing among Mexicans with historical trends and comparisons to other groups.

```{r}
# homeownership = read.csv("Data Tables/3.A.homeownership.csv" )

table_a3 <-  homeownership %>% 
  
  filter(ownershp_f == "Owned or being bought (loan)") %>% 

  pivot_wider(id_cols =  c(race_ethnicity, ownershp_f), names_from = "year", values_from = c(count, per, per2)) %>% 

  mutate(diff2000_2022 = count_2022 - count_2000,
         diff_per = round(per_2022 - per_2000, 4), 
         diff_per2 = paste0(diff_per,"%")
         ) %>% 
  select(race_ethnicity, count_2000, per2_2000, count_2012, per2_2012, count_2022, per2_2022, diff2000_2022, diff_per2) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
      col.names = c("", "Number", "Percent" , "Number", "Percent", "Number", "Percent", "Number", "Percent"),
      align = c("l",rep("c",8)),
      caption = "Homeownership by Race/Ethnicity in Chicago, 2000, 2008-2012, and 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2:9, width = "3.8em") %>%
  add_header_above( align = c("l", rep("c",4)), c("Race/Ethnicity", "2000" = 2, "2008-2012" = 2, "2018-2022" = 2, "Change from\n2000 to 2018-2022" = 2),
                    # background = "#cbc9e2", 
                    bold = T, font_size =8) %>% 
  # row_spec(0, bold = T, 
  #          # background = "#f2f0f7",
  #          font_size = 8) %>% 
  
  footnote(general = "Source: IPUMS-USA database (2000, 2008-2012, 2018-2022). Tabulations by Great Cities Institute",
           general_title = "")   

table_a3

```


## 3.B1: Number and percentage of Mexicans who, live in crowded housing, or are rent-burdened.

```{r}

# usa_ddi2 <- read_ipums_micro(read_ipums_ddi("C:/Users/elhamp2/Box/Great Cities Institute/Research/Mexican Report/usa_00002.xml"))
#
# housing_ddi2 <- usa_ddi2 %>%
#   select(YEAR, MULTYEAR, RACE, RACED, CITY, PUMA, HISPAN, PERNUM, PERWT,HHWT, SERIAL, ROOMS, NUMPREC ) %>%
#   clean_names()


## Be careful rooms == 0 is NA but it is overcrowded
overcrowded = housing_ddi %>%
  filter( city == 1190, pernum == 1, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not?
  mutate(race_f = as_factor(race),
         hispan_f = as_factor(hispan)) %>%

   mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>% 

  as_survey_design(weights = hhwt) %>%
  survey_count(year, race_ethnicity, rooms, numprec, name="count") %>%
  mutate(p_per_room = numprec/rooms,
         overcrowded = if_else(p_per_room >1, "Overcrowded", "Not Overcowded")) %>%

  group_by(year, race_ethnicity) %>%
  mutate(total = sum(count, na.rm = T)) %>%
  filter(rooms != 0 ) %>%  ## rooms == 0 is NA but it is overcrowded
  ungroup() %>%
  group_by(year, race_ethnicity, overcrowded, total) %>%

  summarise(count_sum = sum(count)) %>%
  mutate(per = 100*round(count_sum/total, 4),
         per2 = paste0(per,"%")) %>%
  ungroup()

```



```{r}

table_3.b1 <- overcrowded %>%

  filter(overcrowded == "Overcrowded" ) %>%

  select(race_ethnicity, count_sum , per2) %>%

   # using kable

  kbl(, booktabs = T,
      col.names = c("Race/Ethnicity", "Number", "Percent"  ),
      align = c("l",rep("c",2)),
      caption = "Number and Percentage of Households Living in Crowded Housing
      by Race/Ethnicity in Chicago, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = T,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:3, width = "12.9em") %>%
  # add_header_above( c("Race/Ethnicity", "2000" = 2, "2008-2012" = 2, "2018-2022" = 2, "Change from\n2000 to 2018-2022" = 2),
  #                   # background = "#cbc9e2",
  #                   bold = T, font_size =8) %>%
  row_spec(0, bold = T,
           # background = "#f2f0f7",
           font_size = 8) %>%

  footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute",
           general_title = "")

table_3.b1

```


## 3.B2: Rent burdened

```{r}
# housing_ddi3 <- usa_ddi %>%
#   select(YEAR, MULTYEAR, RACE, RACED, CITY, PUMA, HISPAN, PERNUM, PERWT, HHWT, SERIAL, RENTGRS, HHINCOME, OWNCOST) %>%
#   clean_names()



rent_burdened = housing_ddi %>%
  filter( city == 1190, pernum == 1, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not?
  mutate(race_f = as_factor(race),
         hispan_f = as_factor(hispan)) %>%

   mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>% 

  group_by(race_ethnicity) %>%
  mutate(total = sum(hhwt, na.rm = T)) %>%
  ungroup() %>%
  filter(hhincome != 9999999 ) %>%
  filter(rentgrs!= 0) %>%

  mutate(rent_income = rentgrs/hhincome,
         burdened_30 = if_else(rent_income >0.3 , "More than 30%","Less than 30%"),
         burdened_50 = if_else(rent_income >0.5, "More than 50%", "Less than 50%")) %>%

  as_survey_design(weights = hhwt) %>%
  survey_count(year, race_ethnicity, total, burdened_30, burdened_50 , name="count") %>%
  mutate(per = 100*round(count/total, 4),
         per2 = paste0(per,"%"))


####### prepare data for the table

table_3.b2 = rent_burdened %>%
  filter( burdened_30 != "Less than 30%") %>%
  group_by(race_ethnicity ) %>%

  summarise(more_30_count = sum(count[burdened_30== "More than 30%"]),
            more_50_count = sum(count[burdened_50== "More than 50%"]),
            more_30_per = 100 *round(more_30_count/total, 4),
            more_30_per2 = paste0(more_30_per, "%"),
            more_50_per = 100 *round(more_50_count/total, 4),
            more_50_per2 = paste0(more_50_per, "%")) %>%
  distinct()



table_3.b2_2 <- table_3.b2 %>%
  select(race_ethnicity, more_30_count, more_30_per2, more_50_count, more_50_per2) %>%

  # using kable

  kbl(booktabs = T,
      col.names = c("", "Number", "Percent" , "Number", "Percent" ),
      align = c("l",rep("c",4)),
      caption = "Rent Burdened by Race/Ethnicity in Chicago, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:5, width = "6.45em") %>%
  add_header_above( align = c("l", rep("c",2)), c("Race/Ethnicity", "More than 30%" = 2, "More than 50%" = 2),
                    # background = "#cbc9e2",
                    bold = T, font_size =8) %>%
  # row_spec(0, bold = T,
  #          # background = "#f2f0f7",
  #          font_size = 8) %>%

  # footnote(general = "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute.Rent Burdened Households Defined as Spending 30% or More of Income on Rent",
  #          general_title = "") %>% 
  add_footnote(c("Rent Burdened Households Defined as Spending 30% or More of Income on Rent", "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute"),
 notation = "none")
  

table_3.b2_2
```

## 3.B3: Own Cost Burdened

```{r}

owncost_burdened = housing_ddi %>%
  filter( city == 1190, pernum == 1, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not?
  mutate(race_f = as_factor(race),
         hispan_f = as_factor(hispan)) %>%

   mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_)) %>% 
  mutate(race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)"))) %>% 

  group_by(race_ethnicity) %>%
  mutate(total = sum(hhwt, na.rm = T)) %>%
  ungroup() %>%
  filter(hhincome != 9999999 ) %>%
  filter(owncost!= 99999) %>%

  mutate(owncost_income = owncost/hhincome,
         burdened_30 = if_else(owncost_income >0.3 , "More than 30%","Less than 30%"),
         burdened_50 = if_else(owncost_income >0.5, "More than 50%", "Less than 50%")) %>%

  as_survey_design(weights = hhwt) %>%
  survey_count(year, race_ethnicity, total, burdened_30, burdened_50 , name="count") %>%
  mutate(per = 100*round(count/total, 4),
         per2 = paste0(per,"%"))



####### prepare data for the table

table_3.b3 = owncost_burdened %>%
  filter( burdened_30 != "Less than 30%") %>%
  group_by(race_ethnicity ) %>%

  summarise(more_30_count = sum(count[burdened_30== "More than 30%"]),
            more_50_count = sum(count[burdened_50== "More than 50%"]),
            more_30_per = 100 *round(more_30_count/total, 4),
            more_30_per2 = paste0(more_30_per, "%"),
            more_50_per = 100 *round(more_50_count/total, 4),
            more_50_per2 = paste0(more_50_per, "%")) %>%
  distinct()



table_3.b3_2 <- table_3.b3 %>%
  select(race_ethnicity, more_30_count, more_30_per2, more_50_count, more_50_per2) %>%

  # using kable

  kbl(booktabs = T,
      col.names = c("", "Number", "Percent" , "Number", "Percent" ),
      align = c("l",rep("c",4)),
      caption = "Own Cost Burdened by Race/Ethnicity in Chicago, 2018-2022",
      format.args = list(big.mark = ","),
      linesep = "", table.attr = "style='width:30%;'") %>%
 kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>%
  column_spec(1, width = "14.2em") %>%
  column_spec(2:5, width = "6.45em") %>% 
  add_header_above(align = c("l", rep("c",2)), c("Race/Ethnicity", "More than 30%" = 2, "More than 50%" = 2),
                    # background = "#cbc9e2",
                    bold = T, font_size =8) %>%
  # row_spec(0, bold = T,
  #          # background = "#f2f0f7",
  #          font_size = 8) %>%

  
  add_footnote(c("Own Cost Burdened Households Defined as ?", "Source: IPUMS-USA database (2018-2022). Tabulations by Great Cities Institute"),
 notation = "none")

table_3.b3_2
```


## 3.D:



