---
title: ""
author: ""
date: ""
output: 
  pdf_document:
    latex_engine: xelatex
    toc: false
    highlight: pygments
    extra_dependencies: ["float"]
    fig_caption: true
mainfont: "Arial"
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}}
  - \posttitle{\end{flushleft}}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.pos="H")


```


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}

library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(janitor)
library(data.table)
library(tinytex)
library(survey) # for survey analysis
library(srvyr)  # for tidy survey analysis
library(tmap)
library(readr)
library("kableExtra") 
library(tmaptools)
library("RColorBrewer") 
# library(OpenStreetMap)
# remotes::install_github('yihui/knitr')
# install.packages("knitr")
# library(knitr)
# options(tinytex.verbose = TRUE)
# tinytex::reinstall_tinytex()
# install.packages('tinytex')

# update.packages(ask = FALSE, checkBuilt = TRUE)
# tinytex::tlmgr_update()
# tinytex::latexmk("Housing_Visual.tex")
options(knitr.kable.NA = '-') 

# Read Data

usa_data <- read.csv("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/final_Mexican_IL_2000_22.csv") %>% 
  mutate(race_ethnicity = case_when(hispan ==0 & race == 1 ~ "White (non-Hispanic or Latino)",
                                    hispan ==0 & race == 2 ~ "Black (non-Hispanic or Latino)",
                                    hispan %in% c(2,3,4) ~ "Other Hispanics or Latinos",
                                    hispan ==1 ~ "Mexican", 
                                    hispan ==0 & race %in%c(3:9) ~ "Other (non-Hispanic or Latino)",
                                    TRUE ~ NA_character_),
         
  race_ethnicity = factor(race_ethnicity, level = c("Mexican", "Other Hispanics or Latinos","White (non-Hispanic or Latino)", "Black (non-Hispanic or Latino)",  "Other (non-Hispanic or Latino)")),
  
  hispan_breakdown = case_when(
  hispand == 0 ~ "Not Hispanic",
  hispand == 100 ~ "Mexican", 
  hispand == 200 ~ "Puerto Rican",
  hispand == 300 ~ "Cuban",
  hispand == 411 ~ "Costa Rican",
  hispand == 412 ~ "Guatemalan",
  hispand == 413 ~ "Honduran",
  hispand == 414 ~ "Nicaraguan",
  hispand == 415 ~ "Panamanian",
  hispand == 416 ~ "Salvadoran",
  hispand == 417 ~ "Central American, not specified",
  hispand == 420 ~ "Argentinean",
  hispand == 421 ~ "Bolivian",
  hispand == 422 ~ "Chilean",
  hispand == 423 ~ "Colombian",
  hispand == 424 ~ "Ecuadorian",
  hispand == 425 ~ "Paraguayan",
  hispand == 426 ~ "Peruvian",
  hispand == 427 ~ "Uruguayan",
  hispand == 428 ~ "Venezuelan",
  hispand == 431 ~ "South American, not specified",
  hispand == 450 ~ "Spaniard",
  hispand == 460 ~ "Dominican",
  hispand == 498 ~ "Other, not specified",
  TRUE ~ "Other"
),
mex_foreign_born = case_when(
    race_ethnicity == "Mexican" & bpl %in% as.character(1:56) ~ "U.S. Born",
    race_ethnicity == "Mexican" & bpl == "200" ~ "Mexico Born",
    TRUE ~ NA_character_  # Optional: default case for other values or groups
  )) %>% ## filter for hispanic groups here ##
 mutate(hispan_breakdown = factor(hispan_breakdown, level = c("Mexican", "Puerto Rican","Ecuadorian", "Cuban", "Guatemalan", "Colombian"))
  )


# Construct the full file path
chicago_ca_pop <- read_sf("Data Tables/shp/comm_pop_chi_2022.shp") %>% as.data.frame() 

##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>% 
  st_transform(crs = 4326)
# mapview(community_shp)

# Get the current bounding box of the data
bbox_data <- st_bbox(Chicago_boundary_shp)

# Calculate the range of x and y values in degrees
xrange <- bbox_data$xmax - bbox_data$xmin
yrange <- bbox_data$ymax - bbox_data$ymin

# Calculate the center of the bounding box
center_x <- (bbox_data$xmin + bbox_data$xmax) / 2
center_y <- (bbox_data$ymin + bbox_data$ymax) / 2
# Modify the bounding box to fit the desired width while keeping the height the same
bbox_new <- c(center_x - 0.24,
              center_y - 0.23,
              center_x + 0.23,
              center_y + 0.23)

# osm_chicago <- read_osm(bbox_new, 
#                         type = "bing")



theme_plots <-
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(color="#969696", linewidth = 1),
        plot.title = element_text(face ="bold", size = 10, hjust = 0.5),
      plot.subtitle = element_text(face ="italic", size = 8, color = "#636363"),
      axis.text = element_text(size = 9),
      axis.title = element_text(face ="bold", size = 9),
      plot.caption = element_text(hjust = 0, size = 8, color = "black"),
      legend.text = element_text(size = 8, color = "#636363"),
      legend.title = element_text(face = "bold", size = 8, color = "#636363")) 



color_hispan_breakdown <- c(
  "Mexican" = "#CE1126", 
  "Puerto Rican" = "#32C2DC", 
  "Ecuadorian" =  "#A9AD72",
  "Cuban" = "#AB6E29", 
  "Guatemalan" =  "#D3A668",
  "Colombian" = "#F9C93C"
)

color_race_ethnicity <- c("Mexican" = "#CE1126", "Other Hispanics or Latinos" = "#F9AA51",
                               "White (non-Hispanic or Latino)" = "#9CA168",
                               "Black (non-Hispanic or Latino)" = "#8CBEC0",
                               "Other (non-Hispanic or Latino)" = "#0B8489")

race_group = c(Prc_Ownership_With_Employees = "#4D2B18",
               prc_pop = "#D3A668")

school_indicator <- read_csv("School/df_school.csv")


chicago_health <- read_csv("Health Data/Chicago Health Atlas Data Download - Community areas.csv") %>% clean_names() %>% rename(
  obesity_rate = hcsobp_2022_2023,
  diabetes_rate = hcsdiap_2022_2023,
  asthma_rate = hcsathp_2022_2023,
  lbw_rate = vrbwp_2017_2021,
  unmet_mental_health_rate = hcsumhap_2022_2023,
  cancer_diagnosis_rate = ccr_2017_2021,
  hyper_tension_rate = hcshytp_2022_2023,
  psych_distress_rate =   hcsspdp_2022_2023,
  lung_cancer_rate =ccg_2017_2021,
  loneliness_rate = chavqos_2022_2023
)


# merge chicago ca with health atlas
df_health <- chicago_ca_pop %>% select(commnty, prc_mxc, prc_nh_w, prc_nh_b) %>% mutate(commnty = str_to_title(tolower(commnty))) %>% left_join(chicago_health, by = c("commnty" = "name")) %>% select(-layer)  %>%
 mutate(across(matches("rate$"), ~ format(round(as.numeric(.), 1), nsmall = 1))) %>% mutate(across(ends_with("rate"), ~ as.numeric(as.character(.))))

comm_2000_2022 <- st_read ("Data Tables/shp/comm_pop_chi_2000_2022.shp" ) %>% 
  mutate(prc2 = paste0(prc, "%"))


```


```{r include=FALSE}
##### Chicago boarder
Chicago_boundary_shp <- read_sf("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/Boundaries_Chicago/geo_export_8881adc5-2460-457b-892f-04f4d6028b72.shp") %>%
  st_transform(crs = 4326)
# mapview(community_shp)
collar_county_border <- st_read("C:/Users/dsegovi2/Box/Great Cities Institute/Research/Mexican Report/cb_2018_us_county_500k/cb_2018_us_county_500k.shp") %>%
  filter(GEOID %in% c(17043, 17089, 17031, 17097, 17111, 17197)) %>%
  st_transform(crs = 4326) %>%
  select(GEOID,NAME, geometry) %>%
  mutate(label = paste0(NAME, " County"))



pop_county_chicago_1990_2020 <- read_csv("Data Tables/mxc_county_chicago_1990_2020.csv") %>%
  ungroup() %>%
  select(-`...1`) %>%
  # filter(county != "Cook County") %>%
  mutate(year = factor(year, level = c( "1990", "2000", "2010", "2018-2022"))) %>%
  mutate(county = factor(county, level = c("Chicago", "Cook County outside of Chicago" ,"Cook County", "Kane County", "Lake County", "DuPage County", "Will County", "McHenry County"))) %>%
  arrange(year, county) %>%
  mutate(county = if_else(county == "Cook County outside of Chicago","Cook County Outside of Chicago" ,county
                          ))

latino_Chi_county_2000_2020 <- read_csv("Data Tables/latino_Chi_county_2000_2020.csv")

county_pop_1990_2020 <- pop_county_chicago_1990_2020 %>% 
  mutate(prc_mex_his = round(100 *(mexican/total_his), 1),
            prc_mex_total = round(100 * (mexican/total_pop), 1)) %>%
  
  mutate(prc_mex_his2 = paste0(format(round(prc_mex_his, 1), nsmall = 1), "%"),
         prc_mex_total2 = paste0(format(round(prc_mex_total, 1), nsmall = 1), "%"))

msa_table_ownership_income <- read_csv("Data Tables/msa_table_ownership_income.csv")

county_table_ownership_income <- read_csv("Data Tables/county_table_ownership_income.csv")

```


\renewcommand{\arraystretch}{1.4}












```{r}
# Create the data frame with percentages rounded to one decimal place
city_data <- data.frame(
  City = c("Los Angeles", "San Antonio", "Houston", "Phoenix", "Chicago", 
           "El Paso", "Dallas", "San Diego", "New York City", "Fort Worth"),
  
   Total_Population = c(3881041, 1445662, 2296253, 1609456, 2710105, 
                       677181, 1300642, 1383987, 8622467, 924663),
  
   Total_Latino = c(1865763, 951823, 1029429, 691205, 787050, 
                   552434, 551447, 416630, 2503005, 325185),
  
  Percent_Latino = c(48.1, 65.8, 44.8, 43.0, 29.0, 
                     81.6, 42.4, 30.1, 29.0, 35.2),
  
   Total_Mexican = c(1196186, 808918, 686373, 607389, 581376, 
                    519100, 449290, 353790, 338119, 271493),
  
 
  Percent_Mexican = c(30.8, 56.0, 29.9, 37.7, 21.5, 
                      76.7, 34.5, 25.6, 3.9, 29.4),
 
  
  Percent_Latino_Mexican = c(64.1, 85.0, 66.7, 87.9, 73.9, 
                             94.0, 81.5, 84.9, 13.5, 83.5)
 
)


       
       
city_data <- city_data %>% mutate(
   mutate(across(matches("(?i)^Percent|Percent"), ~ paste0(format(round(.x, 1), nsmall = 1), "%")))
)

table_1 <- city_data %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
       col.names = c("City Name", "Total Population", "Hispanic or Latino Population", "% Hispanic or Latino of Total Population",  "Total Mexican Population",  "% Mexicans of Total Population", "% Mexicans of Hispanic or Latino Population"),
      align = c("l",rep("r",6)),
      caption = "Mexican Population for 10 Cities with the Largest Share of Mexican Population, 2018-2022 (ACS 5-year Estimates)",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "7em") %>%
  column_spec(2:7, width = "5.5em") %>%  

  row_spec(0, bold = T, align = "c",
             #background = "#f2f0f7",
            font_size = 7.5) %>%
# Adding footnotes with proper formatting and alignment
add_footnote(
  c(
    "\\footnotesize{\\par\\hspace{-0.5cm} Data Sources: IPUMS NHGIS, University of Minnesota, www.nhgis.org (2018-2022 American Community 
    \\par\\hspace{-0.5cm} Survey 5-year Estimates).Tabulations by Great Cities Institute. 2018-2022 American Community 
    \\par\\hspace{-0.5cm} Survey 5-year Estimates, U.S. Census Bureau, https://data.census.gov.}"
  ),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)


table_1
```


```{r}
table_2 <- msa_table_ownership_income %>% select(metro_name, total_pop, total_mexican,  prc_mexican, avg_incwage, weighted_median_incwage, per2) %>% 
 
   # using kable 
  
  kbl(, booktabs = T,
       col.names = c("Metro Name", "Total Population", "Total Mexican Population",  "% Mexicans of Total Population", "Mean Income", "Median Income", "Mexican Home Ownership Rate"),
      align = c("l",rep("r",6)),
      caption = "Mexican Population, Income, and Mexican Homeownership Rate for 10 Metropolitan Areas with the Largest Share of Mexican Population, 2018-2022 (ACS 5-year Estimates)",
      format.args = list(big.mark = ","),
      linesep = "")  %>% 
  kable_classic(full_width = F,  
                font_size = 8,
                html_font = "Arial",
                position = "center",
                latex_options = "HOLD_position") %>% 
  column_spec(1, width = "14.2em") %>%
  column_spec(2:7, width = "5.1em") %>%  

  row_spec(0, bold = T, align = "c",
             #background = "#f2f0f7",
            font_size = 7.5) %>%
  add_footnote(
  c("\\footnotesize{\\par\\hspace{-0.5cm} Note: The data includes all employed individuals, regardless of whether they work full-time or part-time.}",
    "\\footnotesize{\\par\\hspace{-0.5cm} Data Source: IPUMS USA, University of Minnesota, www.ipums.org (2018-2022 American Community Survey 5-year \\par\\hspace{-0.5cm} Estimates). Tabulations by Great Cities Institute.}"
    
  ),
  notation = "none",
  threeparttable = TRUE,
  escape = FALSE
)

table_2
```


\clearpage


```{r}

occupation2 <- usa_data %>%
  filter( city == 1190, year == 2022) %>%  #### dont forget to filter PUMA   ## Should I filter pernum or not?

  as_survey_design(weights = perwt) %>%
  survey_count(race_ethnicity, occ, employment=empstat_f, name="count") %>%
  filter(employment == "Employed") %>%
  group_by(occ) %>%
  mutate(total_employed = sum(count, na.rm = T)) %>%
  mutate(prc = 100* round(count/total_employed, 4),
         prc2 = paste0(format(round(prc, 1), nsmall = 1), "%")) %>%
  filter(!is.na(occ)) %>%
  ungroup()


top_occ_mxc <- occupation2 %>%
  filter(race_ethnicity == "Mexican") %>%
  arrange(desc(count)) %>%
  slice(1:10) %>%
  pull(occ)

top_occ_latinos <- occupation2 %>%
  filter(race_ethnicity == "Other Hispanics or Latinos") %>%
  arrange(desc(count)) %>%
  slice(1:10) %>%
  pull(occ)



occupation3 <- occupation2 %>%
  filter(occ %in% top_occ_mxc & race_ethnicity == "Mexican"|
         occ %in% top_occ_latinos & race_ethnicity == "Other Hispanics or Latinos") %>%

  mutate(sub_Occupation = case_when(occ == 4220 ~ "Janitors and building cleaners",
                                    occ == 9620 ~ "Laborers and freight, stock, and material movers, hand",
                                    occ == 4020 ~ "Cooks",
                                    occ == 4720 ~ "Cashiers",
                                    occ == 9130 ~ "Driver/sales workers and truck drivers",
                                    occ == 5240 ~ "Customer service representatives",
                                    occ == 6260 ~ "Construction laborers",
                                    occ == 4760 ~ "Retail salespersons",
                                    occ == 4110 ~ "Waiters and waitresses",
                                    occ == 8990 ~ "Miscellaneous production workers, including equipment operators and tenders",
                                    occ == 440 ~ "Other managers",
                                    occ == 4700 ~ "First-line supervisors of retail sales workers"),
  Occupation_group = case_when(occ == 4220 ~ "Service Occupations",
                               occ == 9620 ~ "Transportation and Material Moving Occupations",
                               occ == 4020 ~ "Service Occupations",
                               occ == 4720 ~ "Sales and Related Occupations",
                               occ == 9130 ~ "Transportation and Material Moving Occupations",
                               occ == 5240 ~ "Office and Administrative Support Occupations",
                                occ == 6260 ~ "Construction and Extraction Occupations",
                               occ == 4760 ~ "Sales and Related Occupations",
                               occ == 4110 ~ "Service Occupations",
                               occ == 8990 ~ "Production Occupations",
                               occ == 440 ~ "Management, Business, and Financial Occupations",
                               occ == 4700 ~ "Sales and Related Occupations"

                                    )) %>%
  arrange(factor(race_ethnicity, levels = levels(occupation2$race_ethnicity)), desc(count)) %>%
  ungroup()

##########


table_5a.3_2 <-  occupation3 %>%

  select(Occupation_group, sub_Occupation, count,  prc2) %>%

   # using kable
  kable(booktabs = T,
        col.names = c("Occupation Group","Sub-occupation ", "Number", "% Share of Occupation Employment"   ),
      align = c("l","l" ,rep("r",2)),
      caption = "Employment by Sub-occupation and Percent Share of Occupation Employment for 10 Sub-occupations Where Hispanics or Latinos Have the Highest Number of Employees for Mexicans and Other Hispanics or Latinos in Chicago, 2018-2022 (ACS 5-year Estimates)",
      format.args = list(big.mark = ","),
      linesep = "") %>%
  kable_classic(full_width = F,
                font_size = 8,
                html_font = "Arial",
                position = "center",
                # latex_options = "HOLD_position",
                ) %>%
  column_spec(1:2, width = "20em") %>%
  column_spec(3, width = "5em") %>%
  column_spec(4, width = "6em") %>% 
  # add_header_above( c("Race/Ethnicity", "2000" = 2, "2008-2012" = 2, "2018-2022" = 2, "Change from\n2000 to 2018-2022" = 2),
  #                   # background = "#cbc9e2",
  #                   bold = T, font_size =8) %>%
  row_spec(0, bold = T, align = "c",
           # background = "#f2f0f7",
           font_size = 7.5) %>%
  pack_rows("Mexican", 1,10, hline_after = T, indent=FALSE ) %>%
  pack_rows("Other Hispanics or Latinos", 11, 20, hline_before = T , hline_after = T, indent=FALSE) %>% 
  # add_footnote(
  #   c("\\footnotesize{Data Source: IPUMS USA, University of Minnesota, www.ipums.org (2018-2022 American Community Survey 5-year Estimates). Tabulations by Great Cities Institute.}"),
  #   notation = "none",
  #   threeparttable = TRUE,
  #   escape = FALSE
  # )
footnote(general = "\\\\footnotesize{\\raggedright Data Source: IPUMS USA, University of Minnesota, www.ipums.org (2018-2022 American Community Survey 5-year Estimates). Tabulations by Great Cities Institute.}",
         general_title = "",
         threeparttable = TRUE,
         escape = FALSE)




table_5a.3_2


```