---
title: "Mexicans in Chicago Report Draft"
output:
  html_document:
    toc: true
    theme: united
---
```{r setup, include=FALSE}
library(ipumsr)
library(tidyverse)
library(purrr)
library(sf)
library(tidycensus)
library(tidyr)
library(readxl)
library(sf)
library(htmltools)
library(leaflet)
library(knitr)

getwd()

# import tract files
tract_pop_2018_2022_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/tract_pop_2018_2022_sf/tract_pop_2018_2022_sf.shp") 

tract_pop_2008_2012_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/tract_pop_2008_2012_sf/tract_pop_2008_2012_sf.shp") 

tract_pop_2000_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/tract_pop_2000_sf/tract_pop_2000_sf.shp") 


# import sf files

chicago_ca_2018_22_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/chicago_ca_2018_22_sf/chicago_ca_2018_22_sf.shp") %>% rename(community =  commnty, AQYYE004_sum =  AQYYE00)

chicago_ca_2008_12_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/chicago_ca_2008_12_sf/chicago_ca_2008_12_sf.shp") %>% rename(community =  commnty, Q2OE004_sum = Q2OE004)

chicago_ca_2000_sf <- st_read("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/chicago_ca_2000_sf/chicago_ca_2000_sf.shp")



```




## Demographics 

### 1A Mexican Population 2018-2022 {.tabset} 


#### By Community Area
```{r, echo = FALSE}
# Convert to sf object if not already
chicago_ca_2018_22_sf<- st_as_sf(chicago_ca_2018_22_sf)
# Create a color palette
palette <- colorNumeric(
  palette = "YlOrRd",
  domain = chicago_ca_2018_22_sf$AQYYE004_sum  
)

# Create the leaflet map
leaflet(chicago_ca_2018_22_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(AQYYE004_sum),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(chicago_ca_2018_22_sf$community), function(i) {
      htmltools::HTML(
        paste(
          "<b>Community Area:</b>", chicago_ca_2018_22_sf$community[i], "<br>",
          "<b>Mexican Population Sum:</b>",  format(chicago_ca_2018_22_sf$AQYYE004_sum[i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~AQYYE004_sum,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```



####  By Census Tract

```{r, echo = FALSE}
# Convert to sf object if not already
tract_pop_2018_2022_sf <- st_as_sf(tract_pop_2018_2022_sf )
# Create a color palette
palette <- colorNumeric(
  palette = "YlOrRd",
  domain = tract_pop_2018_2022_sf $AQYYE004 
)

# Create the leaflet map
leaflet(tract_pop_2018_2022_sf ) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(AQYYE004),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(tract_pop_2018_2022_sf$TRACTA), function(i) {
      htmltools::HTML(
        paste(
          "<b>Tract:</b>", tract_pop_2018_2022_sf$TRACTA[i], "<br>",
          "<b>Mexican Population Estimate:</b>", format(tract_pop_2018_2022_sf$AQYYE004[i], big.mark = ",", scientific = FALSE),"<br>",
          "<b>Mexican Population Margin of Error:</b>", format(tract_pop_2018_2022_sf$AQYYM004[i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~AQYYE004,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```



### Mexican Population 2008-2012 {.tabset} 


#### By Community Area
```{r, echo = FALSE}
# Convert to sf object if not already
chicago_ca_2008_12_sf <- st_as_sf(chicago_ca_2008_12_sf)
# Create a color palette
palette <- colorNumeric(
  palette = "BuPu",
  domain = chicago_ca_2008_12_sf$Q2OE004_sum 
)

# Create the leaflet map
leaflet(chicago_ca_2008_12_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(Q2OE004_sum),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(chicago_ca_2008_12_sf$community), function(i) {
      htmltools::HTML(
        paste(
          "<b>Community Area:</b>", chicago_ca_2008_12_sf $community[i], "<br>",
          "<b>Mexican Population Estimate:</b>",  format(chicago_ca_2008_12_sf$Q2OE004_sum [i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~Q2OE004_sum ,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```



####  By Census Tract

```{r, echo = FALSE}
# Convert to sf object if not already
tract_pop_2008_2012_sf <- st_as_sf(tract_pop_2008_2012_sf)
# Create a color palette
palette <- colorNumeric(
  palette = "BuPu",
  domain = tract_pop_2008_2012_sf $Q2OE004 
)

# Create the leaflet map
leaflet(tract_pop_2008_2012_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(Q2OE004),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(tract_pop_2008_2012_sf$TRACTA), function(i) {
      htmltools::HTML(
        paste(
          "<b>Tract:</b>", tract_pop_2008_2012_sf$TRACTA[i], "<br>",
          "<b>Mexican Population Estimate:</b>", format(tract_pop_2008_2012_sf$Q2OE004[i], big.mark = ",", scientific = FALSE), "<br>",
          "<b>Mexican Population Margin of Error:</b>",  format(tract_pop_2008_2012_sf$Q2OM004[i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~Q2OE004,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```


### Mexican Population 2000 {.tabset} 


#### By Community Area
```{r, echo = FALSE}
# Convert to sf object if not already
chicago_ca_2000_sf <- st_as_sf(chicago_ca_2000_sf)
# Create a color palette
palette <- colorNumeric(
  palette ="RdPu",
  domain = chicago_ca_2000_sf$FUH001_sum
)

# Create the leaflet map
leaflet(chicago_ca_2000_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(FUH001_sum),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(chicago_ca_2000_sf$community), function(i) {
      htmltools::HTML(
        paste(
          "<b>Community Area:</b>", chicago_ca_2000_sf$community[i], "<br>",
          "<b>Mexican Population Sum:</b>",  format(chicago_ca_2000_sf$FUH001_sum [i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~FUH001_sum ,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```



####  By Census Tract

```{r, echo = FALSE}
# Convert to sf object if not already
tract_pop_2000_sf <- st_as_sf(tract_pop_2000_sf)
# Create a color palette
palette <- colorNumeric(
  palette = "RdPu",
  domain = tract_pop_2000_sf$FUH001 
)

# Create the leaflet map
leaflet(tract_pop_2000_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~palette(FUH001 ),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = lapply(seq_along(tract_pop_2000_sf$TRACTA), function(i) {
      htmltools::HTML(
        paste(
          "<b>Tract:</b>", tract_pop_2000_sf$TRACTA[i], "<br>",
          "<b>Mexican Population Estimate:</b>", format(tract_pop_2000_sf$FUH001 [i], big.mark = ",", scientific = FALSE)
        )
      )
    }),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = palette,
    values = ~FUH001 ,
    opacity = 0.7,
    title = "Mexican Population",
    position = "bottomright"
  )
```

### 1B: Population Pyramid and median age {.tabset} 

#### pop pyramid


```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}

pop_pyramid <- read_csv("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/pop_pyramid.csv") %>% select(-...1)



kable(pop_pyramid, col.names = c("Group", "Age Group", "Weighted Population Number", "Weighted Percentage (%)"), format = "markdown")

```

#### median age

```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
age  <- read_csv("C:/Users/dsegovi2/Documents/mexico_report/Data Tables/weighted_median_age.csv") %>% select(-...1)


kable(age, col.names = c("Group", "Weighted Median Age"), format = "markdown")

```

