

library(readxl)
# read in relevant columns, filter for chicago public school elementary schools
df_chronic_abst <- read_excel("School/23-RC-Pub-Data-Set.xlsx", , sheet = "General") %>% clean_names()  # Replace "SheetName" with the actual name of the sheet)

# read chicago shapefile

chicago_ca_pop <- read_sf("Data Tables/shp/comm_pop_chi_2022.shp") %>% select(commnty, geometry)




df_chronic_abst2 <- df_chronic_abst  %>% filter(city == "Chicago" & school_type %in% c("ELEMENTARY") & district == "City of Chicago SD 299") %>% select(rcdts, type, school_name, district, city, school_type, chronic_absenteeism, chronic_absenteeism_hispanic_or_latino)

df_proficiency <- read_excel("School/23-RC-Pub-Data-Set.xlsx", , sheet = "ELA Math Science") %>% clean_names()  # Replace "SheetName" with the actual name of the sheet)

df_proficiency2 <- df_proficiency  %>% filter(city == "Chicago" & school_type %in% c("ELEMENTARY") & district == "City of Chicago SD 299") %>% select(rcdts, type, school_name, district, city, school_type, percent_ela_proficiency, percent_ela_proficiency_hispanic_or_latino, percent_math_proficiency, percent_math_proficiency_hispanic_or_latino, percent_science_proficiency, percent_science_proficiency_hispanic_or_latino)

# merge school report card
df_school_report_card <- df_chronic_abst2 %>% full_join(df_proficiency2)  


# remove text to merge accurately

# import school coordinates

df_school_locations <- st_read("School/Chicago Public Schools - School Locations SY2324_20240801/geo_export_ec075c56-327e-479e-a678-a5d28bd258a0.shp") %>% 
  st_transform(crs = 4326) %>% filter(grade_cat == "ES") %>% rename(school_name_2 = short_name)  %>% mutate(school_name_2 = str_to_title(school_name_2),
  school_name_2 = str_trim(school_name_2)) %>% as.data.frame() %>% arrange(school_name_2)

# remove text to merge accurately

# Updated list of terms to remove


terms_to_remove <- c("Elem School", "Multicultural Elem", "Elem Community Academy", "Elementary School", "Elem Regional Gifted Ct", "Elem Bilingual & Intl Ctr", "Elem Academy", "Technology Academy", "Elem Scholastic Academy", "Elem Comp Math & Sci Ctr",  "Elem Magnet Academic Ctr", "Comm Arts & Sci Elem Sch", "Elem Math & Science Acad", "Math & Sci Specialty Elem", " Elem Multicultural Acad C", "Elem Career Academy", "Elem Inclusive Academy", "Primary School", "Acad",  "Elem Community Acad",  "Elem Language Arts Ctr", "Elem Language Academy",  "Elem Comm Acd Fine Arts Ct", "Elem Dual Language Academy", "Elem Language Arts Ctr", "Academy of Social Justice",  "Technology Acad Elem Sch", "Elem Regional Gifted Cntr", "Academy", "Elem Magnet School", "Elem Magnet School", "School of Fine Arts", "Elem IntL Studies", "Community", "Magnet", "Early Childhood Center", "Elem Specialty School", "emy", "Math-Sci Tech", "of Social Justice", "Classical",  "of Fine Arts", "Elem Opt for Knowl School", "Elem Fine Arts Center", "Elem Math & Sci Schol Acd", "Math & Sci", "Elem Fine & Perf Arts Sch", "Middle School",  "Elem  School", "Elem Gifted  School", "Corporate  Elem", "Elem School", "Elem Gifted School", "Corporate  Elem", "Academy", "Elem  School", "Elem Intl Studies School", "Elem  School", "Elem Paideia Comm", "Math-Science Elem Sch", " Elem Learning Center", "Elem Bilingual Center", "North Elem Sch", "Fine Arts Elem Sch", "Elem  School", "Elem  School", "Elem Humanities", "Elem Fine Arts & emic C", "Learning")

# Create a single regex pattern to match any of these terms
pattern_2 <- paste(terms_to_remove, collapse = "|")


df_school_report_card_2 <- df_school_report_card  %>% arrange(school_name) %>% mutate(school_name_2 = str_trim(str_replace_all(school_name, pattern_2, ""))) %>%
  mutate(school_name_2 = str_trim(school_name_2)) %>% mutate(school_name_2 = recode(school_name_2,
  "Brown  W" = "Brown W",
  "Avondale - Logandale" = "Avondale-Logandale",
  "Carver"  = "Carver G",
  "Chicago"  =  "Chicago Academy Es",
   "Chicago World Language" = "Chicago World Language Academy",
   "Chavezt"  =  "Chavez", 
  "Clark  G R" = "Clark Es",
   "Colemon J" =  "Colemon",
   "Crown r"  =  "Crown", 
  "Disney II"  = "Disney Ii Es",
    "Bronzeville"   = "Bronzeville Classical",
  "Frazier Perspectives  ES" = "Frazier Prospective",
  "Garcia Lorca"  = "Lorca",
  "Garvey  M"     = "Garvey",
   "Garvy  J"   =  "Garvy", 
   "Graham  A"  = "Graham Es",   
  "Green  W"   = "Green", 
    "Greene N"  =   "Greene",
   "Harriet Tubman" = "Tubman",
  "Hughes  C" = "Hughes C",
   "James R Doolittle" = "Doolittle", 
  "King"   = "King Es",
  "LaSalle" = "Lasalle",
  "LaSalle II Lang  Elem Sch"   = "Lasalle Ii",
  "Langford A"  = "Langford",
  "Lenart r"  = "Lenart",
   "Locke  J"  = "Locke J",
  "Graham"  = "Graham Es",
  "Jordan Elem  School"  = "Jordan",
  "Keller Elem Gifted  School"   = "Keller",
  "Kellman Corporate  Elem" = "Kellman",
  "McAuliffe"    = "Mcauliffe",
 "McCormick"   = "Mccormick",
  "McCutcheon"  = "Mccutcheon",
 "McDade Elem  School" = "Mcdade",
  "McDowell" = "Mcdowell", 
  "McKay" = "Mckay", 
  "McNair" = "Mcnair",
 "McPherson" = "Mcpherson",
  "Minnie Minoso" = "Minoso",
 "Monarcas" = "Monarcas Academy",
 "Morrill Elem  School"   = "Morrill",
 "Ninos Heroes Elem emic Ctr"   = "Ninos Heroes",
 "OKeeffe"    = "Okeeffe",
 "OToole"  = "Otoole", 
 "Ogden" = "Ogden Es",
  "Orozco Elem Fine Arts & Sciences"  = "Orozco",
 "Owens   ES" = "Owens",
 "Pirie Elem Fine Arts & emic C"  = "Pirie",
  "Poe Elem  School" =  "Poe",
  "Pulaski Intl Sch of Chicago" = "Pulaski",
 "Reavis Elem  Spec Schl"   = "Reavis",
 "Ryder Elem  Spec School"    = "Ryder",
  "STEM   Elem"    = "Stem",
 "Seward Elem Communication Arts Ac" = "Seward", 
 "Smith  W"    = "Smith", 
 "Smyth  J"  = "Smyth",
  "Sor Juana Ines de la Cruz" =  "Sor Juana",
  "South Shore" = "South Shore Es",
 "Spry Elem  School"  = "Spry Es",
 "Suder Montessori Elem  Schl"   = "Suder",
 "Sumner Elem  Comm"    = "Sumner",
  "Thorp  J N"  = "Thorp J",
   "Thorp  O A Elem Scholastic"  = "Thorp O",
 "Ward  J"  = "Ward J",
 "Ward  L"  = "Ward L",
   "Washington  G"  = "Washington G Es",
  "Washington  H"  = "Washington H Es",
 "Wells Preparatory"   = "Wells Es",
  "Woodlawn Elem  School"    = "Woodlawn",
  "Woodson South" = "Woodson",
 "Young"  = "Young Es",
  "Alcott"    = "Alcott Es",
 "Bret Harte"  = "Harte"
 
  ))
  
  

# merge the data
df_merged <- df_school_report_card_2 %>% left_join(df_school_locations, by = c("school_name_2" = "school_name_2"))  %>% st_as_sf()



# Perform the spatial join
df_school_final <- st_join(df_merged, chicago_ca_pop, join = st_intersects)

# export the data
write.csv(df_school_final, "School/df_school.csv")










